Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2020-10, with the labels that each got.

#154 Add dedicated missing image icon
  Doc/app_missing_img.png
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher/Images/app_missing_img.png
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: enhancement

#167 plugin/ProcessKiller: enhancements to the kill-all functionality
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Main.cs
Labels: enhancement

#162 Release 1.3.0 | Plugin 1.2.1
  Doc/Default Icons/app_missing_img.png
  Doc/Default Icons/app_missing_img_01.png
  Doc/Default Icons/app_missing_img_01.svg
  Doc/Default Icons/app_missing_img_02.png
  Doc/Default Icons/app_missing_img_02.svg
  Doc/Default Icons/app_missing_img_03.png
  Doc/Default Icons/app_missing_img_03.svg
  Doc/Default Icons/app_missing_img_buttons.png
  Doc/Default Icons/app_missing_img_buttons.svg
  Doc/Default Icons/app_missing_img_fluent.png
  Doc/Default Icons/app_missing_img_fluent.svg
  Doc/Default Icons/app_missing_img_huge.png
  Doc/Default Icons/app_missing_img_huge.svg
  Doc/Default Icons/app_missing_img_lightblue.png
  Doc/Default Icons/app_missing_img_lightblue.svg
  Doc/Default Icons/app_missing_img_lightblue_buttons.png
  Doc/Default Icons/app_missing_img_lightblue_buttons.svg
  Doc/Default Icons/app_missing_img_minimal.png
  Doc/Default Icons/app_missing_img_minimal.svg
  Doc/Default Icons/app_missing_img_minimal_buttons.png
  Doc/Default Icons/app_missing_img_minimal_buttons.svg
  Doc/app_missing_img.png
  Flow.Launcher.Core/Configuration/Portable.cs
  Flow.Launcher.Core/Updater.cs
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
  Flow.Launcher/Images/app_missing_img.png
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Constants.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/FolderLinks/QuickFolderAccess.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Main.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: Release

#165 Fix Encoding Error
  Flow.Launcher/App.xaml.cs
Labels: bug

#180 Add discord badge and update readme
  README.md
Labels: enhancement

#182 Fix calculator copy error
  Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
Labels: bug

#184 Plugin Calculator version bump
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
Labels: bug

#177 Release version bump
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: release

#176 Release 1.3.1
  Flow.Launcher/App.xaml.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  README.md
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: release
