Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2020-04, with the labels that each got.

#13 Fix Process.Start on urls and directories
  Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
  Flow.Launcher/ReportWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.Folder/Main.cs
Labels: bug

#17 Add ClearType to Flow Launcher
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/Themes/Base.xaml
Labels: enhancement

#15 Fix substring scoring
  Flow.Launcher.Infrastructure/StringMatcher.cs
  Flow.Launcher.Test/FuzzyMatcherTest.cs
Labels: bug

#22 Remove default loading of .bat extension files
  Plugins/Flow.Launcher.Plugin.Program/Settings.cs
Labels: enhancement

#18 Fix UWP apps loading
  Flow.Launcher.Test/Flow.Launcher.Test.csproj
  Flow.Launcher.Test/Plugins/ProgramTest.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Labels: bug

#21 Update readme- First cut
  README.md
Labels: Rebrand

#23 Folder plugin- Recursive delete sub folders and files
  Plugins/Flow.Launcher.Plugin.Folder/ContextMenuLoader.cs
Labels: bug

#24 fix typo in IPublicAPI
  Flow.Launcher.Core/Plugin/PluginInstaller.cs
  Flow.Launcher.Plugin/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.PluginManagement/Main.cs
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
Labels: enhancement

#25 Add support for F# plugins
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
  Flow.Launcher.Plugin/AllowedLanguage.cs
  Flow.Launcher.sln
  Plugins/HelloWorldFSharp/HelloWorldFSharp.fsproj
  Plugins/HelloWorldFSharp/Main.fs
  Plugins/HelloWorldFSharp/plugin.json
Labels: enhancement
