Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2020-11, with the labels that each got.

#183 Pinyin library change
  Flow.Launcher.Infrastructure/Alphabet.cs
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/PinyinAlphabet.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
Labels: enhancement, review in progress

#190 Bookmark Plugin fix
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Bookmark.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/Bookmarks.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/EdgeBookmarks.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
Labels: bug, review in progress

#189 Program plugin improvement
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/IProgram.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Labels: enhancement

#160 Fix plugin dependency loading and remove excess duplicate package references
  Directory.Build.targets
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Plugin/PluginAssemblyLoader.cs
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.sln
  Flow.Launcher/Flow.Launcher.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  Plugins/Flow.Launcher.Plugin.Color/Flow.Launcher.Plugin.Color.csproj
  Plugins/Flow.Launcher.Plugin.ControlPanel/Flow.Launcher.Plugin.ControlPanel.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
  Plugins/Flow.Launcher.Plugin.PluginManagement/Flow.Launcher.Plugin.PluginManagement.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
  Plugins/Flow.Launcher.Plugin.Url/Flow.Launcher.Plugin.Url.csproj
  Plugins/Flow.Launcher.Plugin.WebSearch/Flow.Launcher.Plugin.WebSearch.csproj
Labels: bug

#192 Release 1.4.0 + Plugin 1.2.2 + default plugins version bumps
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Color/plugin.json
  Plugins/Flow.Launcher.Plugin.ControlPanel/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginManagement/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: release

#191 Release 1.4.0 | Plugin 1.2.2
  Directory.Build.targets
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Plugin/PluginAssemblyLoader.cs
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
  Flow.Launcher.Infrastructure/Alphabet.cs
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/Image/ImageCache.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Infrastructure/PinyinAlphabet.cs
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.sln
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Bookmark.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/Bookmarks.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/EdgeBookmarks.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Color/Flow.Launcher.Plugin.Color.csproj
  Plugins/Flow.Launcher.Plugin.Color/plugin.json
  Plugins/Flow.Launcher.Plugin.ControlPanel/Flow.Launcher.Plugin.ControlPanel.csproj
  Plugins/Flow.Launcher.Plugin.ControlPanel/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginManagement/Flow.Launcher.Plugin.PluginManagement.csproj
  Plugins/Flow.Launcher.Plugin.PluginManagement/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/IProgram.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/Settings.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/Flow.Launcher.Plugin.Url.csproj
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Flow.Launcher.Plugin.WebSearch.csproj
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: release

#204 Update readme to make it clear for Everything users
  README.md
Labels: enhancement

#202 Add quicklink to customized theme folder
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
Labels: enhancement

#214 Use default system browser
  Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs
  Flow.Launcher/ReportWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#208 Version bump for release 1.5.0 + plugins
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Color/plugin.json
  Plugins/Flow.Launcher.Plugin.ControlPanel/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginManagement/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: release

#207 Release 1.5.0 | Plugin 1.3.0
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/ReportWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Color/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Color/plugin.json
  Plugins/Flow.Launcher.Plugin.ControlPanel/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.ControlPanel/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginManagement/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.PluginManagement/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Program/Logger/ProgramLogger.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  README.md
  SolutionAssemblyInfo.cs
  appveyor.yml
  global.json
Labels: release

#219 version bump for Calculator & Program plugins
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
Labels: release

#221 Fix image flickering
  Flow.Launcher.Infrastructure/Image/ImageCache.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/ViewModel/ResultViewModel.cs
Labels: bug

#222 Allow MissingImgIcon and DefaultIcon to be removed from image cache
  Flow.Launcher.Infrastructure/Image/ImageCache.cs
Labels: enhancement

#225 rebuild json rpc python script
  .gitignore
  JsonRPC/wox.py
  README.md
Labels: bug

#223 fix tray menu translation
  Flow.Launcher.Core/Resource/Internationalization.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug
