Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2020-07, with the labels that each got.

#102 Fix the width of the blur effect
  Flow.Launcher/Themes/BlurBlack.xaml
  Flow.Launcher/Themes/BlurWhite.xaml
Labels: bug

#103 Add plugin: Process Killer
  Flow.Launcher.sln
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Images/app.png
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Main.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/ProcessHelper.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/ProcessResult.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Readme.md
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
Labels: enhancement, plugin/port

#101 Release 1.1.0 | Plugin 1.1.0 | Explorer Plugin 1.1.0
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/code-review.md
  .github/ISSUE_TEMPLATE/discussion.md
  .github/ISSUE_TEMPLATE/feature-request.md
  Flow.Launcher.Core/Configuration/Portable.cs
  Flow.Launcher.Core/Plugin/PluginConfig.cs
  Flow.Launcher.Core/Plugin/PluginInstaller.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
  Flow.Launcher.Core/Updater.cs
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher.Infrastructure/StringMatcher.cs
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
  Flow.Launcher.Test/FuzzyMatcherTest.cs
  Flow.Launcher.sln
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/Themes/BlurBlack.xaml
  Flow.Launcher/Themes/BlurWhite.xaml
  Flow.Launcher/ViewModel/ResultViewModel.cs
  ISSUE_TEMPLATE.md
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Constants.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/EnvironmentVariables.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/FolderLinks/QuickFolderAccess.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginManagement/Main.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Images/app.png
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Main.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/ProcessHelper.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/ProcessResult.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Readme.md
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/HelloWorldCSharp/Images/app.png
  Plugins/HelloWorldCSharp/Main.cs
  Plugins/HelloWorldCSharp/plugin.json
  Plugins/HelloWorldFSharp/HelloWorldFSharp.fsproj
  Plugins/HelloWorldFSharp/Images/app.png
  Plugins/HelloWorldFSharp/Main.fs
  Plugins/HelloWorldFSharp/plugin.json
  Plugins/HelloWorldPython/Images/app.png
  Plugins/HelloWorldPython/main.py
  Plugins/HelloWorldPython/plugin.json
  Scripts/post_build.ps1
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: Release

#108 Fix: include the ProcessKiller plugin in release builds
  Flow.Launcher.sln
Labels: bug

#110 Release 1.1.1
  Flow.Launcher.sln
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: Release

#111 Fix BlurBlack theme suggestion text color not visible
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/BlackAndWhite.xaml
  Flow.Launcher/Themes/BlurBlack.xaml
  Flow.Launcher/Themes/BlurWhite.xaml
  Flow.Launcher/Themes/Darker.xaml
  Flow.Launcher/Themes/Gray.xaml
  Flow.Launcher/Themes/Light.xaml
  Flow.Launcher/Themes/Metro Server.xaml
  Flow.Launcher/Themes/Pink.xaml
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: bug

#112 Release 1.1.2
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/BlackAndWhite.xaml
  Flow.Launcher/Themes/BlurBlack.xaml
  Flow.Launcher/Themes/BlurWhite.xaml
  Flow.Launcher/Themes/Darker.xaml
  Flow.Launcher/Themes/Gray.xaml
  Flow.Launcher/Themes/Light.xaml
  Flow.Launcher/Themes/Metro Server.xaml
  Flow.Launcher/Themes/Pink.xaml
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: Release

#113 Fix auto-suggestions font color for BlurWhite theme
  Flow.Launcher/Themes/BlurWhite.xaml
Labels: bug

#115 Rename missed file during the rebrand
  Flow.Launcher.Infrastructure/Storage/FlowLauncherJsonStorage.cs
Labels: bug, rebrand

#74 Prompt deletion of file or folder
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Constants.cs
Labels: bug

#114 Add update messages to indicate progress
  Flow.Launcher.Core/Updater.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
Labels: enhancement

#120 Exclude directory/network path for Web Search plugin
  Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
Labels: bug

#122 Various UI fixes and enhancements
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/FodyWeavers.xml
  Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/SettingsControl.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/SettingsControl.xaml.cs
  Plugins/Flow.Launcher.Plugin.Url/SettingsControl.xaml
  Plugins/Flow.Launcher.Plugin.Url/SettingsControl.xaml.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml.cs
Labels: bug, enhancement

#121 Add chromium Edge bookmark loading
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/Bookmarks.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/EdgeBookmarks.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
Labels: enhancement

#125 Move Everything plugin to its own repo
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher.Infrastructure/Exception/ExceptionFormatter.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.sln
  Flow.Launcher/Helper/ErrorReporting.cs
  Plugins/Flow.Launcher.Plugin.Everything/.gitattributes
  Plugins/Flow.Launcher.Plugin.Everything/.gitignore
  Plugins/Flow.Launcher.Plugin.Everything/Everything/EverythingAPI.cs
  Plugins/Flow.Launcher.Plugin.Everything/Everything/EverythingApiDllImport.cs
  Plugins/Flow.Launcher.Plugin.Everything/Everything/Exceptions/CreateThreadException.cs
  Plugins/Flow.Launcher.Plugin.Everything/Everything/Exceptions/CreateWindowException.cs
  Plugins/Flow.Launcher.Plugin.Everything/Everything/Exceptions/IPCErrorException.cs
  Plugins/Flow.Launcher.Plugin.Everything/Everything/Exceptions/InvalidCallException.cs
  Plugins/Flow.Launcher.Plugin.Everything/Everything/Exceptions/InvalidIndexException.cs
  Plugins/Flow.Launcher.Plugin.Everything/Everything/Exceptions/MemoryErrorException.cs
  Plugins/Flow.Launcher.Plugin.Everything/Everything/Exceptions/RegisterClassExException.cs
  Plugins/Flow.Launcher.Plugin.Everything/Everything/ResultType.cs
  Plugins/Flow.Launcher.Plugin.Everything/Everything/SearchResult.cs
  Plugins/Flow.Launcher.Plugin.Everything/EverythingSDK/x64/Everything.dll
  Plugins/Flow.Launcher.Plugin.Everything/EverythingSDK/x86/Everything.dll
  Plugins/Flow.Launcher.Plugin.Everything/EverythingSettings.xaml
  Plugins/Flow.Launcher.Plugin.Everything/EverythingSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.Everything/Flow.Launcher.Plugin.Everything.csproj
  Plugins/Flow.Launcher.Plugin.Everything/Images/error.png
  Plugins/Flow.Launcher.Plugin.Everything/Images/file.png
  Plugins/Flow.Launcher.Plugin.Everything/Images/find.png
  Plugins/Flow.Launcher.Plugin.Everything/Images/folder.png
  Plugins/Flow.Launcher.Plugin.Everything/Images/image.png
  Plugins/Flow.Launcher.Plugin.Everything/Images/warning.png
  Plugins/Flow.Launcher.Plugin.Everything/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Everything/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Everything/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Everything/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Everything/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Everything/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Everything/Main.cs
  Plugins/Flow.Launcher.Plugin.Everything/README.md
  Plugins/Flow.Launcher.Plugin.Everything/Settings.cs
  Plugins/Flow.Launcher.Plugin.Everything/plugin.json
  README.md
Labels: enhancement
