Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2020-12, with the labels that each got.

#235 Add space for pinyin translation
  Flow.Launcher.Infrastructure/PinyinAlphabet.cs
Labels: enhancement

#231 Add PluginsManager for managing PluginsManifest repo
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Plugin/PluginInstaller.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Infrastructure/Http/Http.cs
  Flow.Launcher.Plugin/IPublicAPI.cs
  Flow.Launcher.sln
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.PluginManagement/Flow.Launcher.Plugin.PluginManagement.csproj
  Plugins/Flow.Launcher.Plugin.PluginManagement/Flow.Launcher.PluginResult.cs
  Plugins/Flow.Launcher.Plugin.PluginManagement/Images/plugin.png
  Plugins/Flow.Launcher.Plugin.PluginManagement/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.PluginManagement/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.PluginManagement/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.PluginManagement/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.PluginManagement/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.PluginManagement/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.PluginManagement/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.PluginManagement/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginManagement/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
  Plugins/Flow.Launcher.Plugin.PluginsManager/Images/pluginsmanager.png
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Models/PluginsManifest.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Models/UserPlugin.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Settings.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Utilities.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Views/PluginsManagerSettings.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Views/PluginsManagerSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: enhancement

#238 Add link to website in readme
  README.md
Labels: enhancement

#226 Update LICENSE
  LICENSE
  README.md
  attribution.md
Labels: rebrand

#239 Plugin installation and uninstallation restart without prompt
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: enhancement

#242 Add context menu for PluginsManager
  Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Images/request.png
  Plugins/Flow.Launcher.Plugin.PluginsManager/Images/sourcecode.png
  Plugins/Flow.Launcher.Plugin.PluginsManager/Images/website.png
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: enhancement

#243 Update plugins via Pluginsmanager
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Models/UserPlugin.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Settings.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: enhancement

#247 Update plugin usage in README
  README.md
Labels: enhancement

#246 Update url website in Settings
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: enhancement

#249 Plugin manager improve
  Flow.Launcher.Infrastructure/Http/Http.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Models/PluginsManifest.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Settings.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: bug

#251 Remove post build script target of JsonRPC folder copy
  Scripts/post_build.ps1
Labels: bug

#250 Extract Color plugin from Flow
  Flow.Launcher.sln
  Plugins/Flow.Launcher.Plugin.Color/Flow.Launcher.Plugin.Color.csproj
  Plugins/Flow.Launcher.Plugin.Color/Images/color.png
  Plugins/Flow.Launcher.Plugin.Color/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Color/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Color/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Color/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Color/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Color/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Color/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Color/Main.cs
  Plugins/Flow.Launcher.Plugin.Color/plugin.json
Labels: enhancement

#254 add bing search suggestion
  Plugins/Flow.Launcher.Plugin.WebSearch/Settings.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Bing.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
Labels: enhancement

#245 Inform user when checking update fail
  Flow.Launcher.Core/Updater.cs
Labels: bug
