Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2020-08, with the labels that each got.

#131 Fix missing result list preview in Theme tab
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: bug, rebrand

#132 Remove obsolete methods, properties and classes
  Flow.Launcher.Core/Plugin/QueryBuilder.cs
  Flow.Launcher.Infrastructure/Alphabet.cs
  Flow.Launcher.Infrastructure/FuzzyMatcher.cs
  Flow.Launcher.Infrastructure/StringMatcher.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Plugin/Feature.cs
  Flow.Launcher.Plugin/Features/IContextMenu.cs
  Flow.Launcher.Plugin/Features/IExclusiveQuery.cs
  Flow.Launcher.Plugin/Features/IInstantQuery.cs
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Plugin/IPublicAPI.cs
  Flow.Launcher.Plugin/PluginMetadata.cs
  Flow.Launcher.Plugin/Query.cs
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
Labels: enhancement

#127 Fix WebSearch plugin custom icon location
  Flow.Launcher.Infrastructure/UserSettings/DataLocation.cs
  Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSource.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceViewModel.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
Labels: bug

#119 Add file content search for Explorer plugin
  Flow.Launcher.Infrastructure/UserSettings/PluginSettings.cs
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
  Flow.Launcher/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/QueryConstructor.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  README.md
Labels: enhancement

#123 1.2.0 release version bump
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: Release

#141 Fix navigation to localized path when using Explorer plugin
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/QueryConstructor.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: bug

#144 plugin/explorer: ensure environment variable paths are absolute
  Plugins/Flow.Launcher.Plugin.Explorer/Search/EnvironmentVariables.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: enhancement

#147 Release 1.2.1 version bump
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: Release

#146 Release 1.2.1
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/EnvironmentVariables.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/QueryConstructor.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: Release
