Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2021-08, with the labels that each got.

#622 include saving SearchPrecisionScore because it is not public before
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
Labels: bug

#615 Standardise Flow's exe installer + readme update
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  README.md
  Scripts/post_build.ps1
Labels: enhancement

#630 fix actionkeywords inflate when actionkeyword count mismatch in explorer plugin
  Flow.Launcher.Infrastructure/UserSettings/PluginSettings.cs
Labels: bug

#628 Fix PluginsManager's InstallOrUpdate focus
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: bug

#633 Adjust JsonRPCPlugin.cs Exception Handling
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
Labels: bug

#450 No need for the wrapped Lazy instance in image loading.
  Flow.Launcher.Infrastructure/Image/ImageCache.cs
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/ViewModel/ResultViewModel.cs
Labels: bug, review in progress

#629 Fix Explorer's file result subtitle tool tip as file path instead
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: bug

#627 Version bump for 1.8.2 release
  appveyor.yml
Labels: release

#626 Release 1.8.2
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher.Infrastructure/Image/ImageCache.cs
  Flow.Launcher.Infrastructure/UserSettings/PluginSettings.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  README.md
  Scripts/post_build.ps1
  appveyor.yml
Labels: release

#643 Fix WinGet publish due to change installer name
  appveyor.yml
Labels: bug
