Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2021-02, with the labels that each got.

#320 Fix Http Proxy
  Flow.Launcher.Infrastructure/Http/Http.cs
  Flow.Launcher/App.xaml.cs
Labels: bug

#185 Add Acronym Support for Fuzzy Search
  Flow.Launcher.Infrastructure/PinyinAlphabet.cs
  Flow.Launcher.Infrastructure/StringMatcher.cs
  Flow.Launcher.Test/FuzzyMatcherTest.cs
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
Labels: enhancement

#321 Add "" in FilesFolders.OpenPath to be able to open path with ','
  Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
Labels: bug

#325 Fix move method call only restricted to within the same drive
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: bug

#324 Fix python plugin Json Desterilize issue
  Flow.Launcher.Core/Plugin/JsonPRCModel.cs
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#327 Update readme
  README.md
Labels: enhancement

#332 fix incorrect icopath context menu
  Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Images/manifestsite.png
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: bug

#336 Remove setting after uninstalling plugin
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: bug

#335 Use app.ico as icon instead of app.png for setting window
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Images/app.ico
  Flow.Launcher/SettingWindow.xaml
Labels: bug, kind/ui

#326 Release 1.7.1
  Flow.Launcher.Core/Plugin/JsonPRCModel.cs
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Images/app.ico
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
  Plugins/Flow.Launcher.Plugin.PluginsManager/Images/manifestsite.png
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/sk.xaml
  README.md
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: release

#334 Press F5 in query window to reload all plugin data
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/Msg.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  README.md
Labels: enhancement

#330 move ISavable to Flow.Launcher.Plugin\Interfaces
  Flow.Launcher.Plugin/Interfaces/ISavable.cs
Labels: enhancement

#319 Automatic Python installation for Python plugins
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
  README.md
Labels: enhancement

#340 Add copy bookmark's url to clipboard via context menu
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Images/copylink.png
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
Labels: enhancement

#342 Use HttpCompletionOption.ResponseHeadersRead
  Flow.Launcher.Infrastructure/Http/Http.cs
Labels: enhancement

#341 Expand PluginAPI with Log and JsonStorage
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
  Flow.Launcher.Infrastructure/Storage/PluginJsonStorage.cs
  Flow.Launcher.Plugin/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
Labels: enhancement

#78 Fix win32 app loading
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/ApplicationActivationHelper.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/ShellLinkHelper.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/ShObjIdlTlb.dll
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
Labels: bug, review in progress

#79 Fix UWP loading
  Plugins/Flow.Launcher.Plugin.Program/AppxPackagingTlb.dll
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Program/Programs/AppxPackageHelper.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
Labels: bug

#314 Optimize manifest downloading behavior
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: enhancement

#343 Use Channel instead of BufferBlock
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultsForUpdate.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
Labels: enhancement

#331 JSONRPC Async Model
  Flow.Launcher.Core/Plugin/ExecutablePlugin.cs
  Flow.Launcher.Core/Plugin/JsonPRCModel.cs
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher.Core/Plugin/PythonPlugin.cs
Labels: enhancement

#346 Remove unused check for Stream length
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Baidu.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Bing.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Google.cs
Labels: bug

#352 don't remove setting when updating
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: bug

#349 change docs place
  README.md
Labels: enhancement

#348 Remove duplicate entry
  Flow.Launcher/ViewModel/ResultsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: bug

#358 add taskcanceledexception to updater exception catch
  Flow.Launcher.Core/Updater.cs
Labels: bug

#344 filter description existence before passing it to distinct & separate user selected result from hashing
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
Labels: bug

#361 Fix http error
  Flow.Launcher.Infrastructure/Http/Http.cs
  Flow.Launcher.Test/HttpTest.cs
  Flow.Launcher.Test/Plugins/UrlPluginTest.cs
  Flow.Launcher/App.xaml.cs
Labels: bug

#359 Release 1.7.2
  Flow.Launcher.Core/Updater.cs
  Flow.Launcher.Infrastructure/Http/Http.cs
  Flow.Launcher.Test/HttpTest.cs
  Flow.Launcher.Test/Plugins/UrlPluginTest.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: release

#360 Sync Dev with 1.7.2
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: release

#228 Update to .Net5
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Test/Flow.Launcher.Test.csproj
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Properties/PublishProfiles/Net5.0-SelfContained.pubxml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  Plugins/Flow.Launcher.Plugin.ControlPanel/Flow.Launcher.Plugin.ControlPanel.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
  Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
  Plugins/Flow.Launcher.Plugin.Url/Flow.Launcher.Plugin.Url.csproj
  Plugins/Flow.Launcher.Plugin.WebSearch/Flow.Launcher.Plugin.WebSearch.csproj
  README.md
  Scripts/flowlauncher.nuspec
  Scripts/post_build.ps1
  global.json
Labels: enhancement, review in progress

#368 revise access of UserSelectedrecord, Histroy, TopMost setter access to private
  Flow.Launcher/Storage/QueryHistory.cs
  Flow.Launcher/Storage/TopMostRecord.cs
  Flow.Launcher/Storage/UserSelectedRecord.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Bing.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Google.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
Labels: bug
