Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2021-11, with the labels that each got.

#786 Update Slovak translation
  Flow.Launcher/Languages/sk.xaml
Labels: enhancement

#781 Add OnCultureInfoChanged to IPluginI18n
  Flow.Launcher.Core/Resource/Internationalization.cs
  Flow.Launcher.Plugin/Interfaces/IPluginI18n.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Classes/WindowsSetting.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ResultHelper.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/TranslationHelper.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Main.cs
Labels: enhancement

#716 change cultural info when switching language
  Flow.Launcher.Core/Resource/Internationalization.cs
Labels: enhancement

#705 Fix winget update causing incompatibility with always retrieving latest
  appveyor.yml
Labels: bug

#779 Adjust websearch plugin & Small Fix for pluginstore PR & Setting Popup Redesign
  Flow.Launcher/ActionKeywords.xaml
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
  Flow.Launcher/HotkeyControl.xaml
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/PriorityChangeWindow.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/Images/netflix.png
  Plugins/Flow.Launcher.Plugin.WebSearch/Images/youtubemusic.png
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/setting.json
Labels: bug, kind/ui

#789 Update Slovak translation
  Flow.Launcher/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
Labels: bug

#767 Add width in setting and fix max result displayed not reflected in real-time
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: bug

#793 Split Custom Control Template / Change Toggle Control Template
  Flow.Launcher/App.xaml
  Flow.Launcher/PriorityChangeWindow.xaml
  Flow.Launcher/PriorityChangeWindow.xaml.cs
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/SettingWindow.xaml
Labels: enhancement, kind/ui

#782 Default File manager
  Flow.Launcher.Infrastructure/UserSettings/CustomExplorerViewModel.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/SelectFileManagerWindow.xaml
  Flow.Launcher/SelectFileManagerWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
Labels: enhancement

#805 change the default theme for fresh install
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher/App.xaml
Labels: enhancement

#815 Change Icon Render in plugin / plugin store
  Flow.Launcher/SettingWindow.xaml
Labels: bug

#811 Update Slovak translation
  Flow.Launcher/Languages/sk.xaml
Labels: bug

#812 [dev] NotificationVersion
  Flow.Launcher/Notification.cs
Labels: bug

#824 GameMode
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/Images/gamemode.ico
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Properties/Resources.Designer.cs
  Flow.Launcher/Properties/Resources.resx
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#810 Add Animation and Sound / Fix Last Executed Position
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/Helper/SingletonWindowOpener.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/Resources/open.wav
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
Labels: enhancement, kind/ui

#823 Detect URL and install using Plugin Manager
  Flow.Launcher.Core/Plugin/PluginConfig.cs
  Flow.Launcher.Test/PluginLoadTest.cs
  Flow.Launcher.Test/Plugins/PluginInitTest.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Settings.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Views/PluginsManagerSettings.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Views/PluginsManagerSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: enhancement

#838 [dev] Change Icon back to field to maintain backward compatibility
  Flow.Launcher.Plugin/Result.cs
Labels: bug

#837 [dev] Update Korean translation / Change Hardcoded text to string / Add some button colors
  Flow.Launcher/ActionKeywords.xaml
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/PriorityChangeWindow.xaml
  Flow.Launcher/SelectFileManagerWindow.xaml
  Flow.Launcher/SettingWindow.xaml
Labels: enhancement

#840 Switch off the default launch on system start up
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
Labels: enhancement

#841 [dev] Rename DarkMode Label to Color Scheme
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: bug

#847 Provide Flow Launcher program data in Environmental vars
  Flow.Launcher.Core/Plugin/PythonPlugin.cs
Labels: enhancement

#848 Add Clipboard copy to jsonRPC API
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
Labels: enhancement

#835 Hide Apps Path & Adjust program plugin setting panel
  Plugins/Flow.Launcher.Plugin.Program/AddProgramSource.xaml
  Plugins/Flow.Launcher.Plugin.Program/AddProgramSource.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/ProgramSuffixes.xaml
  Plugins/Flow.Launcher.Plugin.Program/ProgramSuffixes.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/Settings.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
Labels: enhancement, kind/ui
