Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2021-06, with the labels that each got.

#461 Fix unparsed property
  Flow.Launcher.Core/Plugin/JsonPRCModel.cs
Labels: bug

#460 change sequence of loading for shell plugin to avoid null reference
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
Labels: bug

#457 update to ExplorerPathActionkeyword branch
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: Explorer Plugin, enhancement

#464 Use JsonLibrary to Parse object, and replace ProcessStartInfo.Arguments with ArgumentList
  Flow.Launcher.Core/Plugin/JsonPRCModel.cs
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher.Core/Plugin/PythonPlugin.cs
Labels: bug

#465 Use where.exe to detect pythonPath easily
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
Labels: enhancement

#466 Add Customized Object Converter, fix Length issue
  Flow.Launcher.Core/Plugin/JsonPRCModel.cs
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher.Core/Resource/JsonObjectConverter.cs
Labels: bug

#469 Fix hide logic
  Flow.Launcher.Core/Plugin/JsonPRCModel.cs
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
Labels: bug

#472 Add Margin When Enabling Box Shadows
  Flow.Launcher.Core/Resource/Theme.cs
Labels: bug, kind/ui

#449 Add specific keyword for path explore in explorer plugin
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Infrastructure/UserSettings/PluginSettings.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/EnvironmentVariables.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: enhancement

#462 Add WinGet Installation Instruction
  README.md
Labels: document, enhancement

#475 Fix plugin documentation link
  README.md
Labels: bug, document

#477 dev branch: switch to python 3.8.9 embeddable
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
Labels: enhancement

#440 stop hiding scroller
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: enhancement

#481 Add backwards compatibility for Everything plugin v1.4.9
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Infrastructure/Storage/ISavable.cs
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
  Flow.Launcher.Infrastructure/Storage/PluginJsonStorage.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#483 [UI/UX] Remove bottom margin of General tab (Settings)
  Flow.Launcher/SettingWindow.xaml
Labels: bug, kind/ui

#484 [UI] Fix `Settings-window` doesn't show back up when minimized in taskbar by user
  Flow.Launcher/Helper/SingletonWindowOpener.cs
Labels: bug

#474 fix storyboard animation control error
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug

#491 Fix ContextMenu bug
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#495 Remove top margin of General tab (Settings)
  Flow.Launcher/SettingWindow.xaml
Labels: kind/ui

#500 dev branch: remove createdump.exe
  Scripts/post_build.ps1
Labels: bug

#498 auto disable shadow when blur is enabled and make query window width dynamic
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/BlurBlack Darker.xaml
  Flow.Launcher/Themes/BlurBlack.xaml
  Flow.Launcher/Themes/BlurWhite.xaml
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: bug

#532 Exception log partial opt
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/Logger/Log.cs
  Flow.Launcher/Helper/ErrorReporting.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultsForUpdate.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Program/Logger/ProgramLogger.cs
Labels: review in progress
