Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2021-03, with the labels that each got.

#372 Change WebSearch default to global
  Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/Settings.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/setting.json
Labels: bug

#376 Fix missing google scholar action keyword
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
Labels: bug

#377 Fix hibernation
  Plugins/Flow.Launcher.Plugin.Sys/Images/hibernate.png
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
Labels: bug

#380 Add Open Log Location command to sys plugin
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
Labels: bug

#378 Added Plugins section with curently compatible plugins
  README.md
Labels: enhancement

#382 Add copy cmd shell plugin
  Plugins/Flow.Launcher.Plugin.Shell/Images/admin.png
  Plugins/Flow.Launcher.Plugin.Shell/Images/copy.png
  Plugins/Flow.Launcher.Plugin.Shell/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
Labels: enhancement

#386 Fix exclusion of Windows Index search for files and folders
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: Explorer Plugin, bug

#387 Add ConfigureWait and cancellation token & remove unnecessary OperationCanceledException
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Baidu.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Bing.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Google.cs
Labels: bug

#389 Optimize startup
  Flow.Launcher.Core/Plugin/PluginConfig.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
Labels: bug

#396 Add documentation link
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: enhancement

#395 Increase the default width and allow user to resize setting window, and reduce the margin for PluginDirectory
  Flow.Launcher/SettingWindow.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
Labels: bug, kind/ui

#393 Make PluginJsonStorage in IPublicAPI become single instance per type
  Flow.Launcher.Plugin/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
Labels: enhancement

#390 Make IPlugin inherit from IAsyncPlugin
  Flow.Launcher.Core/Plugin/PluginAssemblyLoader.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
  Flow.Launcher.Plugin/IPlugin.cs
  Flow.Launcher.Plugin/PluginPair.cs
Labels: enhancement
