Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2021-01, with the labels that each got.

#259 Include all plugin translation files as content
  Flow.Launcher/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  Plugins/Flow.Launcher.Plugin.ControlPanel/Flow.Launcher.Plugin.ControlPanel.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
  Plugins/Flow.Launcher.Plugin.Url/Flow.Launcher.Plugin.Url.csproj
  Plugins/Flow.Launcher.Plugin.WebSearch/Flow.Launcher.Plugin.WebSearch.csproj
Labels: bug, kind/i18n

#261 Use wildcard to include images
  Flow.Launcher/Flow.Launcher.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.ControlPanel/Flow.Launcher.Plugin.ControlPanel.csproj
  Plugins/Flow.Launcher.Plugin.ControlPanel/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/Flow.Launcher.Plugin.Url.csproj
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Flow.Launcher.Plugin.WebSearch.csproj
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
Labels: bug

#263 Add ability to manual reload PluginsManifest data
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: enhancement

#270 Error handling for plugin update
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: bug

#271 Http error handling
  Flow.Launcher.Infrastructure/Http/Http.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
Labels: bug

#272 Use ValueTask instead of Task
  Flow.Launcher/ViewModel/ResultViewModel.cs
Labels: enhancement

#278 Image quality
  Doc/mainsearch.png
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Images/mainsearch.svg
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: enhancement

#275 Create and deploy releases from CI
  Flow.Launcher/Flow.Launcher.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
  Scripts/post_build.ps1
  appveyor.yml
Labels: enhancement

#253 Replace Json.Net with System.Text.Json
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher.Core/Plugin/PluginConfig.cs
  Flow.Launcher.Core/Updater.cs
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/Helper.cs
  Flow.Launcher.Infrastructure/Logger/Log.cs
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Plugin/PluginMetadata.cs
  Flow.Launcher/Storage/QueryHistory.cs
  Flow.Launcher/Storage/TopMostRecord.cs
  Flow.Launcher/Storage/UserSelectedRecord.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/FolderLinks/FolderLink.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSource.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/Settings.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Baidu.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Google.cs
Labels: enhancement, review in progress

#281 1.7.0 version bump
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: release

#284 fix: copy svg images to output from the main project
  Flow.Launcher/Flow.Launcher.csproj
Labels: bug

#283 Slovak translation update
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/sk.xaml
Labels: kind/i18n

#276 Add Plugin Priority Settings
  Flow.Launcher.Infrastructure/UserSettings/PluginSettings.cs
  Flow.Launcher.Plugin/PluginMetadata.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/PriorityChangeWindow.xaml
  Flow.Launcher/PriorityChangeWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/PluginViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
Labels: enhancement, review in progress

#289 Update README.md
  README.md
Labels: enhancement

#288 Version bump for PluginsManager
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: enhancement

#293 fix TopMostRecord and UserSelectedRecord
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
  Flow.Launcher/Storage/TopMostRecord.cs
  Flow.Launcher/Storage/UserSelectedRecord.cs
Labels: bug

#297 Plugin manager init timeout
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: bug

#296 Version bump Flow.Launcher.Plugin
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
Labels: release

#195 Render improvement
  Flow.Launcher.Infrastructure/Image/ImageCache.cs
  Flow.Launcher.Infrastructure/Logger/Log.cs
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Flow.Launcher/ViewModel/ResultsForUpdate.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
Labels: enhancement, kind/ui, review in progress

#300 fix error message not working + increase delay
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: bug

#298 Exclude index search from special chars
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: bug

#310 Use Window Search Orderby
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/QueryConstructor.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: Explorer Plugin, enhancement

#309 Fix unrecognized path
  Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: bug

#295 Stop ProgressBar animation when Flow is hidden
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
Labels: enhancement

#301 Add Cancellation token for file system enumeration
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/FolderLinks/QuickFolderAccess.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: enhancement

#311 Fix untranslated string
  Flow.Launcher.Core/Updater.cs
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingWindow.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Url/SettingsControl.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml
Labels: bug, kind/i18n

#230 Expand Plugin API
  Flow.Launcher.Infrastructure/StringMatcher.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Plugin/IPublicAPI.cs
  Flow.Launcher.Plugin/SharedModels/MatchResult.cs
  Flow.Launcher.Test/FuzzyMatcherTest.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/Bookmarks.cs
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
Labels: enhancement

#316 Update Slovak translation
  Flow.Launcher/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/sk.xaml
Labels: bug

#315 Add save file with Explorer for quick access
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Images/quickaccess.png
  Plugins/Flow.Launcher.Plugin.Explorer/Images/removequickaccess.png
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Constants.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/FolderLinks/QuickFolderAccess.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/AccessLink.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/QuickAccess.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: enhancement
