Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2021-09, with the labels that each got.

#670 Fix File Content action keyword change error
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: bug

#674 Release version bump 1.8.3
  appveyor.yml
Labels: release

#675 Release 1.8.3
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  appveyor.yml
Labels: release

#451 Cache program result
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
Labels: enhancement

#621 Add Quick Access action keyword for Explorer
  Flow.Launcher.Infrastructure/UserSettings/PluginSettings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: enhancement, Explorer Plugin

#623 Add Glyph Icon Support
  Flow.Launcher.Plugin/GlyphInfo.cs
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/ViewModel/ResultViewModel.cs
Labels: enhancement

#647 update python message from install to download
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
Labels: enhancement

#653 Refactor JsonRPC structure
  Flow.Launcher.Core/Plugin/ExecutablePlugin.cs
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher.Core/Plugin/PythonPlugin.cs
  Flow.Launcher.Test/Plugins/JsonRPCPluginTest.cs
Labels: enhancement

#654 Bump applicable nuget packages to latest versions
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Test/Flow.Launcher.Test.csproj
  Flow.Launcher/Flow.Launcher.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
  Scripts/post_build.ps1
Labels: enhancement

#679 Add Advanced Boot Options restart for Sys plugin
  Plugins/Flow.Launcher.Plugin.Sys/Images/restart_advanced.png
  Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
Labels: enhancement

#698 Update Slovak translation
  Plugins/Flow.Launcher.Plugin.Program/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
Labels: bug

#699 Use CDN for PluginsManifest
  Plugins/Flow.Launcher.Plugin.PluginsManager/Models/PluginsManifest.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: enhancement

#702 Implement Requery option and requery when calling customQueryHotkey
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug
