Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2021-07, with the labels that each got.

#537 Check null for ContextMenu
  Flow.Launcher.Core/Plugin/PluginManager.cs
Labels: bug

#538 fix unintended use of direct startInfo.Arguments in context menu
  Flow.Launcher.Core/Plugin/PythonPlugin.cs
Labels: bug

#541 Fix Explorer unexpected action keyword for folder index search
  Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
Labels: Explorer Plugin, bug

#544 Fix (workaround) for the settings-window freezes after lock screen (Win+L)
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
Labels: bug

#550 fix unexpected Task Status
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: bug

#552 Remove Empty Entries in ProgramSuffixes.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/ProgramSuffixes.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
Labels: bug

#555 Update Slovak translation
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/sk.xaml
Labels: bug

#556 JsonRPC camelCase and Case Insensitive
  Flow.Launcher.Core/Plugin/JsonPRCModel.cs
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher/Storage/UserSelectedRecord.cs
Labels: bug

#561 Dispose Disposable or AsyncDisposable plugin on mainwindow close
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug

#563 Move IAsyncReloadable.cs, IReloadable.cs, ISavable.cs to IFeatures
  Flow.Launcher.Plugin/Feature.cs
  Flow.Launcher.Plugin/Features.cs
  Flow.Launcher.Plugin/Interfaces/IAsyncPlugin.cs
  Flow.Launcher.Plugin/Interfaces/IAsyncReloadable.cs
  Flow.Launcher.Plugin/Interfaces/IContextMenu.cs
  Flow.Launcher.Plugin/Interfaces/IPlugin.cs
  Flow.Launcher.Plugin/Interfaces/IPluginI18n.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher.Plugin/Interfaces/IReloadable.cs
  Flow.Launcher.Plugin/Interfaces/IResultUpdated.cs
  Flow.Launcher.Plugin/Interfaces/ISavable.cs
  Flow.Launcher.Plugin/Interfaces/ISettingProvider.cs
  Flow.Launcher.Plugin/README.md
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#562 Json rpc unit test
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Properties/AssemblyInfo.cs
  Flow.Launcher.Test/Flow.Launcher.Test.csproj
  Flow.Launcher.Test/Plugins/JsonRPCPluginTest.cs
Labels: enhancement

#565 Fix flow's hotkey not working correctly after changing in settings
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/HotkeyControl.xaml
  Flow.Launcher/HotkeyControl.xaml.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#548 point pluginsmanifest to new api branch
  Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Models/PluginsManifest.cs
Labels: enhancement

#501 Update README.md
  .github/ISSUE_TEMPLATE/discussion.md.not_used
  README.md
Labels: document, enhancement

#534 Version bump for 1.8.0 release
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  SolutionAssemblyInfo.cs
Labels: release

#573 add comment to explain locale swap
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
Labels: bug

#576 update release version in AppVeyor
  SolutionAssemblyInfo.cs
  appveyor.yml
Labels: enhancement

#583 Update Slovak translation
  Flow.Launcher/Languages/sk.xaml
Labels: bug

#582 Add WinGet update CD
  appveyor.yml
Labels: enhancement

#595 fix animation logic
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug

#590 reduce magnifying glass icon size
  Flow.Launcher/MainWindow.xaml
Labels: enhancement

#596 Add portable release
  README.md
  Scripts/post_build.ps1
  appveyor.yml
Labels: enhancement

#603 Add a MemoryStream buffer to ReadStream first
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
Labels: bug

#609 Fix PluginsManager context menu crashing
  Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: bug

#606 Fix portable readme download link & WinGet pipeline & change Nuget publish on tag only
  README.md
  appveyor.yml
Labels: bug

#605 Version bump for release 1.8.0
  appveyor.yml
Labels: release

#604 Release 1.8.1
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  README.md
  Scripts/post_build.ps1
  appveyor.yml
Labels: release

#620 Delay the create query helper call to avoid Windows Search not running
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: bug
