Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2021-04, with the labels that each got.

#398 add score bumping with query and do hashcode customized
  Flow.Launcher/Storage/UserSelectedRecord.cs
Labels: enhancement, review in progress

#401 Update Slovak translation
  Flow.Launcher/Languages/sk.xaml
Labels: enhancement

#404 save Shell plugin cmd history
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingWindow.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
  Plugins/Flow.Launcher.Plugin.Shell/Settings.cs
  Plugins/Flow.Launcher.Plugin.Shell/ShellSetting.xaml
  Plugins/Flow.Launcher.Plugin.Shell/ShellSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
Labels: enhancement

#409 Allow Quick Access Links to be accessed with middle string
  Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/QuickAccess.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: bug

#407 Fix concurrent access issue
  Flow.Launcher.Core/Plugin/PluginAssemblyLoader.cs
Labels: bug

#410 Remove redundant QuickAccess folder nickname path
  Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/AccessLink.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/QuickAccess.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: bug

#411 Dev branch: Fix optional subtitle
  Flow.Launcher.Plugin/Result.cs
Labels: bug

#415 Add tips and UserData location commands for Sys plugin
  Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
Labels: enhancement

#412 Add API error msg method
  Flow.Launcher.Plugin/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: bug

#419 Update Slovak translation
  Flow.Launcher/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
Labels: bug

#416 Bring Legacy records together
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
  Flow.Launcher/Storage/UserSelectedRecord.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#422 Added and corrected Chinese translation
  Flow.Launcher/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
Labels: bug
