Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2021-12, with the labels that each got.

#741 Add WindowsSettings plugin
  Flow.Launcher.Core/Resource/Internationalization.cs
  Flow.Launcher.Plugin/Interfaces/IPluginI18n.cs
  Flow.Launcher.sln
  Flow.Launcher/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.ControlPanel/ControlPanelItem.cs
  Plugins/Flow.Launcher.Plugin.ControlPanel/ControlPanelList.cs
  Plugins/Flow.Launcher.Plugin.ControlPanel/Flow.Launcher.Plugin.ControlPanel.csproj
  Plugins/Flow.Launcher.Plugin.ControlPanel/Images/ControlPanel.png
  Plugins/Flow.Launcher.Plugin.ControlPanel/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.ControlPanel/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.ControlPanel/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.ControlPanel/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.ControlPanel/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.ControlPanel/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.ControlPanel/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.ControlPanel/Main.cs
  Plugins/Flow.Launcher.Plugin.ControlPanel/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Classes/WindowsSetting.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Flow.Launcher.Plugin.WindowsSettings.csproj
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ContextMenuHelper.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/JsonSettingsListHelper.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ResultHelper.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/TranslationHelper.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/UnsupportedSettingsHelper.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Images/ControlPanel_Small.png
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Images/WindowsSettings.light.png
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Log.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Main.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.Designer.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.cs-CZ.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.de-DE.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.es-ES.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.fr-FR.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.hu-HU.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.it-IT.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.ja-JP.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.ko-KR.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.pl-PL.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.pt-BR.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.pt-PT.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.ru-RU.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.sv-SE.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.tr-TR.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.zh-TW.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.zh-cn.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/README.md
  Plugins/Flow.Launcher.Plugin.WindowsSettings/WindowsSettings.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
Labels: enhancement

#855 Add Portuguese (Portugal) Language
  Flow.Launcher.Core/Resource/AvailableLanguages.cs
Labels: kind/i18n

#849 Welcome window
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/HotkeyControl.xaml
  Flow.Launcher/HotkeyControl.xaml.cs
  Flow.Launcher/Images/page_img01.png
  Flow.Launcher/Images/wizard.png
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage1.xaml
  Flow.Launcher/Resources/Pages/WelcomePage1.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage3.xaml
  Flow.Launcher/Resources/Pages/WelcomePage3.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage4.xaml
  Flow.Launcher/Resources/Pages/WelcomePage4.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage5.xaml
  Flow.Launcher/Resources/Pages/WelcomePage5.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/WelcomeWindow.xaml
  Flow.Launcher/WelcomeWindow.xaml.cs
Labels: enhancement

#862 Fix overlapping of scrollbar and resize area
  Flow.Launcher/SettingWindow.xaml
Labels: bug, kind/ui

#850 Global TAB complete
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/Converters/QuerySuggestionBoxConverter.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultViewModel.cs
Labels: enhancement

#860 Fix misaligned suggestion text
  Flow.Launcher/Converters/QuerySuggestionBoxConverter.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug

#863 Explorer plugin: Support AutoCompleteText Field
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: enhancement, Explorer Plugin

#871 New crowdin translations
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.pt-PT.resx
Labels: enhancement

#834 [dev] Global hotkey refactor
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/Hotkey/GlobalHotkey.cs
  Flow.Launcher.Infrastructure/Hotkey/InterceptKeys.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/HotkeyControl.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
Labels: bug

#657 Json rpc plugin setting control
  Flow.Launcher.Core/Plugin/JsonPRCModel.cs
  Flow.Launcher.Core/Plugin/JsonRPCConfigurationModel.cs
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher.Core/Plugin/PythonPlugin.cs
Labels: enhancement

#800 Global browser setting / Private mode option
  Flow.Launcher.Infrastructure/UserSettings/CustomBrowserViewModel.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/SelectBrowserWindow.xaml
  Flow.Launcher/SelectBrowserWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/CustomBrowserSetting.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/SettingsControl.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/SettingsControl.xaml.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/Main.cs
  Plugins/Flow.Launcher.Plugin.Url/SettingsControl.xaml
  Plugins/Flow.Launcher.Plugin.Url/SettingsControl.xaml.cs
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
Labels: enhancement

#865 Update readme
  Flow.Launcher/SettingWindow.xaml.cs
  README.md
Labels: enhancement, document

#703 Version bump for Flow 1.9.0 | 2.1.0 plugin release
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  appveyor.yml
Labels: release

#887 Refresh Nuget publish
  appveyor.yml
Labels: bug

#888 Small Design Fix in Setting Window
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/PriorityChangeWindow.xaml
  Flow.Launcher/Resources/Pages/WelcomePage3.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Views/PluginsManagerSettings.xaml
Labels: bug

#895 Hotfix toggle switch & Fix Strings
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/SelectBrowserWindow.xaml
  Flow.Launcher/SelectFileManagerWindow.xaml
  Flow.Launcher/SettingWindow.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/CustomBrowserSetting.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/SettingsControl.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Views/CalculatorSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
  Plugins/Flow.Launcher.Plugin.Program/AddProgramSource.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/ProgramSuffixes.xaml
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
  Plugins/Flow.Launcher.Plugin.Shell/ShellSetting.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.ko-KR.resx
Labels: bug, kind/ui

#910 Adjust Vertical Alignment and Margins in JsonSettingPanel
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
Labels: bug, kind/ui

#916 dev version bump plugins for pr 895
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
Labels: bug

#920 Remove Startup Error notification for updating manifest and update check
  Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
  Flow.Launcher.Core/Updater.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: bug

#923 Fix BookmarkDataSetting key string
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/CustomBrowserSetting.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
Labels: bug

#908 fix calling mainwindow animation after loaded
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#918 Add offset to suggestion text hide calculation
  Flow.Launcher/Converters/QuerySuggestionBoxConverter.cs
Labels: bug

#936 Use Dynamic resource for NewTab & NewWindow
  Flow.Launcher/SelectBrowserWindow.xaml
Labels: bug, kind/i18n

#927 Fix typescript plugin request
  Flow.Launcher.Core/Plugin/ExecutablePlugin.cs
Labels: bug

#880 Add crowdin translations
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/sk.xaml
Labels: bug
