Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2022-08, with the labels that each got.

#1306 add sponsor
  Flow.Launcher.Core/Plugin/JsonPRCModel.cs
  README.md
Labels: enhancement

#1299 Fix crash when user does not have access to registry startup keys
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Helper/AutoStartup.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Notification.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: bug

#1147 Add handling of exceptions from plugins
  Flow.Launcher.Core/ExternalPlugins/FlowPluginException.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher/ReportWindow.xaml.cs
Labels: bug

#1341 [Dev] Unregister Cancellation Event by disposing the delegate
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
Labels: bug

#967 Auto re-index for Program and Bookmark plugins
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/FirefoxBookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
Labels: enhancement

#1328 [Dev] Add icons to About tab
  Flow.Launcher/SettingWindow.xaml
Labels: kind/ui
