Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2022-11, with the labels that each got.

#1354 Clock & Date
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/Themes/Atom.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/BlurBlack Darker.xaml
  Flow.Launcher/Themes/BlurWhite.xaml
  Flow.Launcher/Themes/Darker Glass.xaml
  Flow.Launcher/Themes/Darker.xaml
  Flow.Launcher/Themes/Discord Dark.xaml
  Flow.Launcher/Themes/Dracula.xaml
  Flow.Launcher/Themes/Gray.xaml
  Flow.Launcher/Themes/League.xaml
  Flow.Launcher/Themes/Metro Server.xaml
  Flow.Launcher/Themes/Nord Darker.xaml
  Flow.Launcher/Themes/Nord.xaml
  Flow.Launcher/Themes/Pink.xaml
  Flow.Launcher/Themes/Sublime.xaml
  Flow.Launcher/Themes/Win10Light.xaml
  Flow.Launcher/Themes/Win11Dark.xaml
  Flow.Launcher/Themes/Win11Light.xaml
  Flow.Launcher/Themes/Win11System.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: enhancement, kind/ui

#1476 [Program Plugin] Support .url file
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/ProgramSuffixes.xaml
  Plugins/Flow.Launcher.Plugin.Program/ProgramSuffixes.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/Settings.cs
  Plugins/Flow.Launcher.Plugin.Program/SuffixesConverter.cs
Labels: enhancement

#1514 [Dev] Fix unwanted URL protocols and invalid programs in custom sources
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Labels: bug

#1516 Score adjustment for a match that is closer to the start of string
  Flow.Launcher.Infrastructure/StringMatcher.cs
  Flow.Launcher.Test/FuzzyMatcherTest.cs
Labels: enhancement

#1428 Drag and drop
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/ResultListBox.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#930 Custom Query Shortcut + built-in variables
  Flow.Launcher.Infrastructure/Logger/Log.cs
  Flow.Launcher.Infrastructure/UserSettings/CustomShortcutModel.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Converters/TranslationConverter.cs
  Flow.Launcher/CustomShortcutSetting.xaml
  Flow.Launcher/CustomShortcutSetting.xaml.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: enhancement

#1521 [Dev] Fix clipboard shortcut error when clipboard is empty
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#1510 Fix memory leaks with Plugin store layout
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Resources/Dark.xaml
  Flow.Launcher/Resources/Light.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: bug, kind/ui, Code Refactor

#1492 [Program Plugin] Fix UWP icon missing issue
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
Labels: bug

#1529 Appveyor test executable unfound fix and add caching
  appveyor.yml
Labels: bug, enhancement, CI/CD

#1530 [Dev] Save Setting Window State (full / normal)
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/SettingWindow.xaml.cs
Labels: bug

#1479 [Program Plugin] Search programs in PATH
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/Settings.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
Labels: enhancement

#1496 [Program Plugin] Fix program UID and other bugs
  Flow.Launcher.Test/Plugins/ProgramTest.cs
  Plugins/Flow.Launcher.Plugin.Program/AddProgramSource.xaml
  Plugins/Flow.Launcher.Plugin.Program/AddProgramSource.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/FileChangeWatcher.cs
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/Logger/ProgramLogger.cs
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/ApplicationActivationHelper.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/AppxPackageHelper.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/ShellLinkHelper.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/Settings.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/Commands/ProgramSettingDisplay.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/Models/ProgramSource.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
Labels: bug, Code Refactor

#1535 Change the Add program source window to responsive
  Plugins/Flow.Launcher.Plugin.Program/AddProgramSource.xaml
Labels: bug

#1537 [Dev][Program Plugin] Fix uid case of user disabled programs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/Models/ProgramSource.cs
Labels: bug

#1541 [dev] Fix missing text
  Flow.Launcher/Languages/en.xaml
Labels: bug

#1543 [dev] Fix bookmark sql dependency issue
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
Labels: bug

#1547 Deploy prerelease builds to Flow-Launcher/Prereleases
  appveyor.yml
Labels: enhancement, CI/CD

#1546 [Dev][Program Plugin] Optimize program indexing performance
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Labels: bug, Code Refactor

#1550 [Dev] Allow branch builds and do not skip md files
  appveyor.yml
Labels: bug

#1551 Fix #1546
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Labels: bug

#1536 Fix freezing in Plugin list
  Flow.Launcher/SettingWindow.xaml
Labels: bug

#1548 Fix Narrow Items & Adjust Context Menu Design
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher/HotkeyControl.xaml
  Flow.Launcher/HotkeyControl.xaml.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/Resources/Dark.xaml
  Flow.Launcher/Resources/Light.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
Labels: kind/ui, kind/i18n

#1545 Refactor pinyin alphabet and bugfix
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/PinyinAlphabet.cs
  Flow.Launcher.Infrastructure/StringMatcher.cs
  Flow.Launcher.Infrastructure/pinyindb/pinyin_gwoyeu_mapping.xml
  Flow.Launcher.Infrastructure/pinyindb/pinyin_mapping.xml
  Flow.Launcher.Infrastructure/pinyindb/unicode_to_hanyu_pinyin.txt
  Flow.Launcher.Test/FuzzyMatcherTest.cs
Labels: bug, Code Refactor

#1562 [Dev] Use path of lnk file when launching proram
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Labels: bug

#1561 [Dev] Refactor KeyBinding Commands
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#1556 [Dev] Improve Clock/Date
  Flow.Launcher/Converters/DateTimeFormatToNowConverter.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/Metro Server.xaml
  Flow.Launcher/Themes/Pink.xaml
  Flow.Launcher/Themes/Win10Light.xaml
  Flow.Launcher/Themes/Win11Light.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: bug

#1351 Allow plugins to use web URL's for icon paths
  Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
  Flow.Launcher.Core/Updater.cs
  Flow.Launcher.Infrastructure/Http/Http.cs
  Flow.Launcher.Infrastructure/Image/ImageCache.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/Msg.xaml.cs
  Flow.Launcher/ViewModel/PluginViewModel.cs
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceViewModel.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Bing.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Google.cs
Labels: enhancement, review in progress

#1569 Add 'Become A Sponsor' Button
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: enhancement

#1570 Change Windows Settings plugin Keyword to s from *
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
Labels: bug

#1566 Improve Themes
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/Themes/Atom.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/BlackAndWhite.xaml
  Flow.Launcher/Themes/BlurBlack Darker.xaml
  Flow.Launcher/Themes/BlurBlack.xaml
  Flow.Launcher/Themes/Bullet Light.xaml
  Flow.Launcher/Themes/Circle Light.xaml
  Flow.Launcher/Themes/Circle System.xaml
  Flow.Launcher/Themes/Cyan Dark.xaml
  Flow.Launcher/Themes/Darker Glass.xaml
  Flow.Launcher/Themes/Darker.xaml
  Flow.Launcher/Themes/Discord Dark.xaml
  Flow.Launcher/Themes/Dracula.xaml
  Flow.Launcher/Themes/League.xaml
  Flow.Launcher/Themes/Light.xaml
  Flow.Launcher/Themes/Metro Server.xaml
  Flow.Launcher/Themes/Midnight.xaml
  Flow.Launcher/Themes/Nord Darker.xaml
  Flow.Launcher/Themes/Nord.xaml
  Flow.Launcher/Themes/Pink.xaml
  Flow.Launcher/Themes/Sublime.xaml
  Flow.Launcher/Themes/Ubuntu.xaml
  Flow.Launcher/Themes/Win10Light.xaml
  Flow.Launcher/Themes/Win11Dark.xaml
  Flow.Launcher/Themes/Win11Light.xaml
  Flow.Launcher/Themes/Win11System.xaml
  Flow.Launcher/ViewModel/ResultsViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: bug, kind/ui, Code Refactor

#1571 [Dev] Update Wizard ('Bluetooth' to 's Bluetooth')
  Flow.Launcher/Languages/da.xaml
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/fr.xaml
  Flow.Launcher/Languages/it.xaml
  Flow.Launcher/Languages/ja.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/nl.xaml
  Flow.Launcher/Languages/pl.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/ru.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/sr.xaml
  Flow.Launcher/Languages/tr.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/Languages/zh-tw.xaml
Labels: bug, kind/i18n

#1574 [Dev] Fix typos in source string
  Flow.Launcher/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
Labels: bug

#1554 Add Illustrations in custom query windows
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/CustomShortcutSetting.xaml
  Flow.Launcher/Images/illustration_01.png
  Flow.Launcher/Images/illustration_02.png
  Flow.Launcher/Languages/en.xaml
Labels: kind/ui

#1573 New Crowdin updates
  Flow.Launcher/Languages/da.xaml
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/fr.xaml
  Flow.Launcher/Languages/it.xaml
  Flow.Launcher/Languages/ja.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/nl.xaml
  Flow.Launcher/Languages/pl.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/ru.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/sr.xaml
  Flow.Launcher/Languages/tr.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.es-EM.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.pt-PT.resx
Labels: bug, kind/i18n

#1575 Fix Focus hotkey box when change tab
  Flow.Launcher/SettingWindow.xaml
Labels: bug

#1579 Fix Theme Preview area
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: bug

#1395 Loading bookmarks by browser
  Flow.Launcher.sln
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/BookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Models/Settings.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/SettingsControl.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/SettingsControl.xaml.cs
Labels: enhancement

#1589 Add Focus to plugin/plugin store search box when changed tab
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
Labels: enhancement

#1581 Refactor UWP class in Program plugin
  Flow.Launcher.Test/Plugins/ProgramTest.cs
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/ApplicationActivationHelper.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/AppxPackageHelper.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Labels: bug, Code Refactor
