Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2022-01, with the labels that each got.

#942 fix move cursor to the end when it is not called from main thread
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug

#938 Update XML Docs
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Plugin/GlyphInfo.cs
  Flow.Launcher.Plugin/Result.cs
Labels: bug

#911 Plugin activation icon
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#917 Display hotkey in tray context menu
  Flow.Launcher/MainWindow.xaml.cs
Labels: enhancement

#952 Fix Toggle Switch Knob (White Circle) Positioning
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/SettingWindow.xaml
Labels: bug

#948 Update plugin language list + update flow's website
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher.Infrastructure/Logger/Log.cs
  Flow.Launcher/ViewModel/PluginViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
  README.md
Labels: enhancement

#951 Fix incorrect text for "New Tab" and "New Window" buttons
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/ReportWindow.xaml.cs
  Flow.Launcher/SelectBrowserWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: bug, kind/i18n

#953 stop trigger global hotkey when shell plugin is not enabled
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
Labels: bug

#978 Minor enhancements to query auto-completion
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Main.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
Labels: enhancement

#974 Fix spellings in translation keys
  Flow.Launcher/Languages/da.xaml
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/fr.xaml
  Flow.Launcher/Languages/it.xaml
  Flow.Launcher/Languages/ja.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/nb-NO.xaml
  Flow.Launcher/Languages/nl.xaml
  Flow.Launcher/Languages/pl.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/ru.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/sr.xaml
  Flow.Launcher/Languages/tr.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.ControlPanel/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Settings.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/setting.json
Labels: bug

#972 Improvements to PluginManager plugin
  Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
  Flow.Launcher.Infrastructure/Http/Http.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Settings.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Labels: enhancement

#963 Use Microsoft Package to handle toast notification for registry
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Notification.cs
Labels: bug

#983 Add scoop install to readme
  Flow.Launcher/App.xaml.cs
  README.md
Labels: enhancement

#935 Revise ttf/otf code
  Flow.Launcher/ViewModel/ResultViewModel.cs
Labels: bug

#858 Ctrl + Backspace in Query goes up directory path
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#987 [Dev] Add support for action keyword when using Ctrl + Backspace
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
  README.md
Labels: bug

#991 Open plugin website from context menu
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#851 Global copy to clipboard
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#968 Support Application Uri in OpenUrl API call
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs
  Flow.Launcher/PublicAPIInstance.cs
Labels: enhancement
