Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2022-04, with the labels that each got.

#1119 Remove All Cleartype Rendering
  Flow.Launcher/Themes/Base.xaml
Labels: bug, kind/ui

#1104 Add Stale issue workflow
  .github/ISSUE_TEMPLATE/workflows/stale.yml
Labels: enhancement

#1108 Respect Decimal Separator for query not just result
  Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Settings.cs
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
Labels: bug
