Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2022-07, with the labels that each got.

#1270 Update Stale bot
  .github/workflows/stale.yml
Labels: CI/CD

#969 Move Tasklink Name into Resource (except altName) & Glyph Icon Support
  Flow.Launcher.Core/Resource/Internationalization.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Classes/WindowsSetting.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Flow.Launcher.Plugin.WindowsSettings.csproj
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ResultHelper.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/TranslationHelper.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.Designer.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.cs.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.de.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.es.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.fr.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.hu.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.it.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.ja.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.ko.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.pl.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.ru.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.sv.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.tr.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/WindowsSettings.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
Labels: enhancement

#1098 Scroll to selected item when expanded or size changed
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
Labels: bug, kind/ui

#1204 fix RemoveOldQueryResults NullPointerException
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#1005 Use Cancellation Token to avoid potential race tracing issue
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
Labels: bug

#1123 Implement Async Result Execution
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher.Test/Plugins/JsonRPCPluginTest.cs
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#1121 Pass query without trimming whitespace
  Flow.Launcher.Core/Plugin/QueryBuilder.cs
  Flow.Launcher.Test/QueryBuilderTest.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#1287 Release 1.9.4
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Settings.cs
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
  Plugins/Flow.Launcher.Plugin.Shell/Settings.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.resx
  Scripts/post_build.ps1
  appveyor.yml
Labels: release

#1296 Fix theme fonts not changing separately for query box and results
  Flow.Launcher/SettingWindow.xaml
Labels: bug

#1283 Force reload theme resources when changing fonts etc in settings
  Flow.Launcher.Core/Resource/Theme.cs
Labels: bug

#1294 Fix plugin info not displayed when it has multiple actionkeywords
  Flow.Launcher/SettingWindow.xaml
Labels: bug
