Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2022-12, with the labels that each got.

#1593 Fix Second Run not trigger the first run window to show up
  Flow.Launcher/App.xaml.cs
Labels: bug

#1097 Merge Explorer & Everything Plugins
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/EverythingSDK/x64/Everything.dll
  Plugins/Flow.Launcher.Plugin.Explorer/EverythingSDK/x86/Everything.dll
  Plugins/Flow.Launcher.Plugin.Explorer/Exceptions/EngineNotAvailableException.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Exceptions/SearchException.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Helper/ShellContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Helper/SortOptionTranlationHelper.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Images/context_menu.png
  Plugins/Flow.Launcher.Plugin.Explorer/Images/error.png
  Plugins/Flow.Launcher.Plugin.Explorer/Images/everything_error.png
  Plugins/Flow.Launcher.Plugin.Explorer/Images/index.png
  Plugins/Flow.Launcher.Plugin.Explorer/Images/index_error.png
  Plugins/Flow.Launcher.Plugin.Explorer/Images/index_error2.png
  Plugins/Flow.Launcher.Plugin.Explorer/Images/robot_error.png
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Constants.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingAPI.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingApiDllImport.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingDownloadHelper.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchOption.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/Exceptions/CreateThreadException.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/Exceptions/CreateWindowException.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/Exceptions/IPCErrorException.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/Exceptions/InvalidCallException.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/Exceptions/InvalidIndexException.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/Exceptions/MemoryErrorException.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/Exceptions/RegisterClassExException.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/SortOption.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/IProvider/IContentIndexProvider.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/IProvider/IIndexProvider.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/IProvider/IPathIndexProvider.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/QuickAccess.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchResult.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/QueryConstructor.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndex.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndexSearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/ActionKeywordModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/EnumBindingModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/RelayCommand.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/Converters/EverythingEnumNameConverter.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
Labels: enhancement, Explorer Plugin, External Plugin

#1594 [Dev] Fix Drag and Drop causing windows hang
  Flow.Launcher/ResultListBox.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
Labels: bug

#1596 [Dev] fix null reference when clicking on Set Item to Top or plugin website
  Flow.Launcher/ResultListBox.xaml.cs
Labels: bug

#1360 Preview Panel
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/Images/loading.png
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/BlurBlack Darker.xaml
  Flow.Launcher/Themes/BlurBlack.xaml
  Flow.Launcher/Themes/BlurWhite.xaml
  Flow.Launcher/Themes/Bullet Light.xaml
  Flow.Launcher/Themes/Circle Light.xaml
  Flow.Launcher/Themes/Circle System.xaml
  Flow.Launcher/Themes/Cyan Dark.xaml
  Flow.Launcher/Themes/Darker Glass.xaml
  Flow.Launcher/Themes/Darker.xaml
  Flow.Launcher/Themes/Discord Dark.xaml
  Flow.Launcher/Themes/Dracula.xaml
  Flow.Launcher/Themes/Gray.xaml
  Flow.Launcher/Themes/League.xaml
  Flow.Launcher/Themes/Midnight.xaml
  Flow.Launcher/Themes/Nord Darker.xaml
  Flow.Launcher/Themes/Pink.xaml
  Flow.Launcher/Themes/Sublime.xaml
  Flow.Launcher/Themes/Ubuntu.xaml
  Flow.Launcher/Themes/Win10Light.xaml
  Flow.Launcher/Themes/Win11Dark.xaml
  Flow.Launcher/Themes/Win11Light.xaml
  Flow.Launcher/Themes/Win11System.xaml
  Flow.Launcher/ViewModel/PluginViewModel.cs
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
Labels: enhancement, kind/ui

#1605 [Dev] Fix Glyph Icon Size in preview
  Flow.Launcher/Themes/Base.xaml
Labels: bug

#1601 Bump NuGet CommandLine version
  Flow.Launcher/Flow.Launcher.csproj
  Scripts/flowlauncher.nuspec
  Scripts/post_build.ps1
Labels: bug

#1609 [Dev] Bump plugin versions after .Net 6 upgrade
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
Labels: bug

#1611 Fix Program Plugin Buttons Size
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
Labels: bug, kind/ui

#1610 Change hardcoded text to string
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/WelcomeWindow.xaml
Labels: bug, kind/i18n

#1621 [Dev] Fix action keyword missing when traversing paths or using autocomplete
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Labels: bug

#1620 [Dev] Fix duplicate Quick Access results from CreateOpenCurrentFolderResult
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
Labels: bug

#1622 Icon changed & Fix non-glyph context menus
  Flow.Launcher/Images/Browser.png
  Flow.Launcher/Images/app_missing_img.png
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Images/bookmark.png
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Images/calculator.png
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Images/manifestsite.png
  Plugins/Flow.Launcher.Plugin.PluginsManager/Images/pluginsmanager.png
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Images/app.png
  Plugins/Flow.Launcher.Plugin.Program/Images/program.png
  Plugins/Flow.Launcher.Plugin.Shell/Images/shell.png
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
  Plugins/Flow.Launcher.Plugin.Url/Images/url.png
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Images/ControlPanel_Small.png
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Images/WindowsSettings.light.png
Labels: enhancement

#1615 Adjust Plugin info area
  Flow.Launcher/Languages/da.xaml
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/fr.xaml
  Flow.Launcher/Languages/it.xaml
  Flow.Launcher/Languages/ja.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/pl.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/Languages/ru.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/sr.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/Languages/zh-tw.xaml
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/PluginViewModel.cs
Labels: enhancement

#1613 Adjust Setting Panel Layout (System & JsonRPC)
  Flow.Launcher.Core/Plugin/JsonRPCConfigurationModel.cs
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Plugins/Flow.Launcher.Plugin.Sys/SysSettings.xaml
  Plugins/Flow.Launcher.Plugin.Sys/SysSettings.xaml.cs
Labels: bug

#1606 [Dev] Fix shell win+r too slow to appear/does not appear when triggered
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
Labels: bug

#1600 [Dev] Refactor AddProgramSource dialog and bugfix
  Plugins/Flow.Launcher.Plugin.Program/AddProgramSource.xaml
  Plugins/Flow.Launcher.Plugin.Program/AddProgramSource.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/LocationConverter.cs
  Plugins/Flow.Launcher.Plugin.Program/ViewModels/AddProgramSourceViewModel.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/Models/ProgramSource.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
Labels: bug, Code Refactor

#1635 Fix Opening file path containing blanks with editor
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: bug

#1651 Update README.md
  README.md
Labels: bug, document

#1652 Fix the bottom margin issue when loading progress
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/Win10Light.xaml
Labels: bug, kind/ui

#1627 New Crowdin updates
  Flow.Launcher/Converters/OrdinalConverter.cs
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.de-DE.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.pt-BR.resx
Labels: bug, kind/i18n

#1657 Add exception handling when Windows Search service not available
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/QueryConstructor.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndex.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndexSearchManager.cs
Labels: bug

#1667 Fix Progressbar & Margin issue with preview panel
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Themes/Base.xaml
Labels: bug

#1674 Update sponsors
  README.md
Labels: document

#1675 Version bump release 1.10.1
  appveyor.yml
Labels: release

#1639 Release 1.10.1
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
  Flow.Launcher/Converters/OrdinalConverter.cs
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/Win10Light.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/QueryConstructor.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndex.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndexSearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.de-DE.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.pt-BR.resx
  README.md
  appveyor.yml
Labels: release

#1676 Disable PATH programs by default
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/Settings.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
Labels: bug

#1684 Fix item can't be unselected after editing shortcut
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: bug

#1693 Always Start in English Layout
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Converters/BoolToIMEConversionModeConverter.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#1695 Fix text and other issues in Explorer
  Flow.Launcher.Core/Resource/LocalizationConverter.cs
  Flow.Launcher.Core/Resource/LocalizedDescriptionAttribute.cs
  Flow.Launcher.Core/Resource/TranslationConverter.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/SettingWindow.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/DecimalSeparator.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Views/CalculatorSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
Labels: review in progress, kind/i18n

#1701 fix a typo
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
Labels: bug

#1698 Change Status Label to Enabled
  Plugins/Flow.Launcher.Plugin.Program/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml
Labels: bug, kind/i18n

#1669 Add option to enable/disable UWP indexing
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Settings.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
Labels: bug, enhancement

#1711 Update wording for consistency
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
Labels: kind/i18n

#1713 Fix 1705
  Flow.Launcher/CustomShortcutSetting.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
Labels: kind/i18n

#1712 Refactor Toggle Game Mode logic in main window
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#1715 Fix wrong Everything service warning displayed when not available
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Labels: bug

#1706 Fix quick access path search and autocomplete text
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
Labels: bug

#1708 Catch exceptions during shortcut expansion
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#1680 Add "hh:mm:ss tt" to clock formats.
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: enhancement

#1719 WindowsSettings plugin - command updated for diskmgmt
  Plugins/Flow.Launcher.Plugin.WindowsSettings/WindowsSettings.json
Labels: bug

#1699 Remove Hiding the Disabled menu Item
  Flow.Launcher/Resources/CustomControlTemplate.xaml
Labels: bug

#1724 Update Explorer plugin description
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: bug

#1725 Fix typo
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
Labels: bug, kind/i18n

#1709 Configurable preview panel toggle hotkey and use lazy load preview image
  Flow.Launcher.Infrastructure/Image/ImageCache.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/Converters/StringToKeyBindingConverter.cs
  Flow.Launcher/Languages/da.xaml
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/fr.xaml
  Flow.Launcher/Languages/it.xaml
  Flow.Launcher/Languages/ja.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/nl.xaml
  Flow.Launcher/Languages/pl.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/ru.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/sr.xaml
  Flow.Launcher/Languages/tr.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/Languages/zh-tw.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
  README.md
Labels: enhancement

#1727 Fix ImageCache when loading full image
  Flow.Launcher.Infrastructure/Image/ImageCache.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
Labels: bug

#1734 New Crowdin updates
  Flow.Launcher.Core/Updater.cs
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sk.xaml
Labels: bug

#1559 Add Winget Releaser workflow
  .github/dependabot.yml
  .github/workflows/winget.yml
Labels: enhancement, CI/CD

#1748 Add prompt for Log Off command
  Plugins/Flow.Launcher.Plugin.Sys/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
Labels: bug

#1744 Spell chek action
  .github/actions/spelling/README.md
  .github/actions/spelling/advice.md
  .github/actions/spelling/allow.txt
  .github/actions/spelling/candidate.patterns
  .github/actions/spelling/excludes.txt
  .github/actions/spelling/expect.txt
  .github/actions/spelling/line_forbidden.patterns
  .github/actions/spelling/patterns.txt
  .github/actions/spelling/reject.txt
  .github/workflows/spelling.yml
Labels: bug, github_actions

#1752 Fix sarif
  .github/actions/spelling/patterns.txt
  .github/workflows/spelling.yml
Labels: bug, github_actions
