Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2022-09, with the labels that each got.

#1355 Adjust Max Width Window Size
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/SettingWindow.xaml
Labels: bug, kind/ui

#1365 Display Drive Space
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/Themes/Base.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Labels: enhancement, kind/ui, review in progress

#1387 Fix opening url twice when clicking on exception report link
  Flow.Launcher/ReportWindow.xaml.cs
Labels: bug

#1388 Spanish & Spanish Latin America languages release for v1.9.5
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/es.xaml
Labels: release

#1381 Special character error in ole db query
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
Labels: bug

#1410 Spanish translation #1409,fix when modifying the language,LastQueryMode's Display no immediate translation
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/Languages/zh-tw.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: bug, kind/i18n

#1391 check query for null
  Flow.Launcher.Core/Plugin/PluginManager.cs
Labels: bug

#1386 Release 1.9.5
  Flow.Launcher.Core/ExternalPlugins/FlowPluginException.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Resource/AvailableLanguages.cs
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Helper/AutoStartup.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Notification.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/ReportWindow.xaml.cs
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  appveyor.yml
Labels: release

#1382 Adjust designs & Texts
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/Themes/BlurBlack Darker.xaml
  Flow.Launcher/Themes/BlurBlack.xaml
  Flow.Launcher/Themes/BlurWhite.xaml
  Flow.Launcher/Themes/League.xaml
  Flow.Launcher/Themes/Win11Light.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
Labels: enhancement, kind/ui

#1427 Remove font-family style for Chinese
  Flow.Launcher/ActionKeywords.xaml
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/PriorityChangeWindow.xaml
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/SelectBrowserWindow.xaml
  Flow.Launcher/SelectFileManagerWindow.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/CustomBrowserSetting.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml
  Plugins/Flow.Launcher.Plugin.Program/AddProgramSource.xaml
  Plugins/Flow.Launcher.Plugin.Program/ProgramSuffixes.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml
Labels: bug

#1431 Fix Blurry Context menu in query box
  Flow.Launcher/Resources/CustomControlTemplate.xaml
Labels: bug
