Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2022-03, with the labels that each got.

#1036 Fix Shared Assembly Issue
  Flow.Launcher.Core/Plugin/PluginAssemblyLoader.cs
Labels: bug

#1002 [Dev] Fix application URI logic when opening via WebSearch plugin
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
Labels: bug

#1056 Fix typo for plugin title in context menu and WindowsSettings name
  Flow.Launcher/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.resx
Labels: bug, kind/ui

#1052 Release 1.9.3
  Flow.Launcher.Core/Plugin/PluginAssemblyLoader.cs
  Flow.Launcher.Infrastructure/Image/ImageCache.cs
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/ReportWindow.xaml.cs
  Flow.Launcher/SelectBrowserWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Baidu.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Bing.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Google.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/SuggestionSource.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ResultHelper.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#1061 Remove obsolete WinGet from appveyor.yml deployment pipeline
  appveyor.yml
Labels: enhancement

#1059 Update readme
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceViewModel.cs
  README.md
Labels: bug

#1071 avoid exception in ChromiumBookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
Labels: bug

#1087 Set Shell plugin's default replace Win R hotkey to off
  Plugins/Flow.Launcher.Plugin.Shell/Settings.cs
Labels: bug

#1088 Add Spanish and Spanish Latin America to language selection
  Flow.Launcher.Core/Resource/AvailableLanguages.cs
Labels: enhancement
