Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2022-10, with the labels that each got.

#1430 Search Source Setting guide text
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml
Labels: kind/i18n

#1383 Fixed Progressbar Binding Error (ProgressBar Value is Not Nullable)
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
Labels: bug

#1380 Fixed QueryTextbox Binding event
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug

#1419 Add Uninstall Button
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
Labels: enhancement

#1352 Rounded icon mask field
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/ViewModel/ResultViewModel.cs
Labels: enhancement

#1368 Remember Setting window Size and Location
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: enhancement, kind/ui

#1374 Add System Commands
  Plugins/Flow.Launcher.Plugin.Sys/Images/indexoption.png
  Plugins/Flow.Launcher.Plugin.Sys/Images/openrecyclebin.png
  Plugins/Flow.Launcher.Plugin.Sys/Images/recyclebin.png
  Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
Labels: enhancement

#892 Implement PluginSearch TextBox & ContentControl Lazy Load
  Flow.Launcher.sln
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/PluginViewModel.cs
Labels: enhancement

#1464 Update readme explaning prs and milestones
  Flow.Launcher.Core/Updater.cs
  README.md
Labels: document

#486 Add github dependency bot
  .github/dependabot.yml
Labels: enhancement

#1369 Shortcuts to adjust width size, number of results shown and game mode
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
  global.json
Labels: enhancement, kind/ui

#1490 Remove ColorProfileData in app_missing_img
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher/Images/app_missing_img.png
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Images/ControlPanel_Small.png
Labels: bug

#1367 Search window's position settings
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: enhancement
