Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2023-03, with the labels that each got.

#1939 Release version bumps
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#1953 Fix Dark Text Color in Everything Panel
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
Labels: bug

#1954 Fix Wikipedia typo in readme
  README.md
Labels: bug

#1960 Add Theme Section Title
  Flow.Launcher/SettingWindow.xaml
Labels: kind/ui

#1959 Remove Obsolete Property and use Status Property for Sorting
  Flow.Launcher/Resources/Dark.xaml
  Flow.Launcher/Resources/Light.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSource.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml.cs
Labels: bug

#1958 Fix the sound issue
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug

#1980 Fix Wrong Version Check in plugin store
  Flow.Launcher/ViewModel/PluginStoreItemViewModel.cs
Labels: bug

#1990 Update bug-report.yaml
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: bug

#1978 Improve Window Position Setting
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Helper/WindowsInteropHelper.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: enhancement, kind/ui
