Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2023-05, with the labels that each got.

#2104 Change default search window position to follow cursor
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
Labels: bug, Dev branch only

#2109 Release version bumps
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#2118 Add sponsor
  README.md
Labels: enhancement, Documentation

#2127 Remove deprecated Everything plugin from readme
  README.md
Labels: bug

#2133 Add plugin API: HideMainWindow(), IsMainWindowVisible()
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
Labels: enhancement

#2137 Plugin Store search (should) work after refresh button clicked
  Flow.Launcher/SettingWindow.xaml.cs
Labels: bug

#2160 Remove NuGet.CommandLine package dependency
  Flow.Launcher/Flow.Launcher.csproj
  Scripts/post_build.ps1
Labels: Code Refactor
