Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2023-01, with the labels that each got.

#1753 fix some spelling
  .github/actions/spelling/expect.txt
  .github/actions/spelling/patterns.txt
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/ProgramSuffixes.xaml
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.Url/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Url/Main.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ResultHelper.cs
Labels: bug

#1750 Allow plugin name to be searchable by Plugin Indicator
  .github/actions/spelling/expect.txt
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
Labels: bug

#1756 Fix crowdin spell check action
  .github/actions/spelling/excludes.txt
  .github/actions/spelling/expect.txt
  .github/actions/spelling/patterns.txt
  .github/workflows/spelling.yml
Labels: bug, github_actions

#1757 Refactor clear log folder logic
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: bug, enhancement

#1759 Add glyph for open with editor/shell
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
Labels: bug, kind/ui

#1736 Use localized name for shell link programs
  Plugins/Flow.Launcher.Plugin.Program/Programs/ShellLinkHelper.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/ShellLocalization.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Labels: kind/i18n

#1760 Stop spell check on push
  .github/workflows/spelling.yml
Labels: bug, Dev branch only, github_actions

#1780 Add slash to active explorer path return string
  Flow.Launcher.Infrastructure/FileExplorerHelper.cs
Labels: bug, Dev branch only

#1768 Dynamic Height and Dynamic Icon Size
  .github/actions/spelling/expect.txt
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Converters/DiameterToCenterPointConverter.cs
  Flow.Launcher/Converters/IconRadiusConverter.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/Dracula.xaml
  Flow.Launcher/Themes/SlimLight.xaml
  Flow.Launcher/Themes/Win11Light.xaml
  Flow.Launcher/Themes/Win11System.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: kind/ui

#1786 Expand builtin shortcuts when needed
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, Dev branch only

#1788 fix explorer setting UseLocationAsWorkingDir
  .github/actions/spelling/expect.txt
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Constants.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/AccessLink.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
Labels: bug

#1781 Always show/search description in program results if enabled
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Labels: bug

#1804 Add sponsor to readme
  README.md
Labels: enhancement, document

#1789 catch exception when killing unused jsonrpc process
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
Labels: bug

#1770 Validate hotkey when setting it
  Flow.Launcher.Infrastructure/Hotkey/HotkeyModel.cs
  Flow.Launcher/HotkeyControl.xaml
  Flow.Launcher/HotkeyControl.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml.cs
Labels: bug

#1817 Fix bugs in explorer plugin
  Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
  Flow.Launcher.Test/FilesFoldersTest.cs
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Exceptions/EngineNotAvailableException.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/EnvironmentVariables.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndexSearchManager.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Labels: bug, review in progress

#1824 Add Maximum/Minimum Priority Value
  Flow.Launcher/PriorityChangeWindow.xaml
Labels: bug

#1762 Safer Updater
  Flow.Launcher.Core/Updater.cs
  Flow.Launcher/App.xaml.cs
Labels: bug

#1763 Atomic Save for Setting
  .github/actions/spelling/expect.txt
  Flow.Launcher.Infrastructure/Helper.cs
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
  Flow.Launcher.Infrastructure/Storage/PluginJsonStorage.cs
Labels: bug

#1830 Version bumps for release 1.12.0
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#1846 Version bump for 1.12.1 release
  appveyor.yml
Labels: release

#1845 Release 1.12.1
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
  appveyor.yml
Labels: release

#1847 Change the default shortcut for Plugin Indicator to `?` #1825
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
Labels: kind/ui
