Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2023-02, with the labels that each got.

#1854 Fix Error of loading backup when original file doesn't exists
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
Labels: bug, review in progress

#1745 Update to .Net 7
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Test/Flow.Launcher.Test.csproj
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Properties/PublishProfiles/Net7.0-SelfContained.pubxml
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
  Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
  Plugins/Flow.Launcher.Plugin.Url/Flow.Launcher.Plugin.Url.csproj
  Plugins/Flow.Launcher.Plugin.WebSearch/Flow.Launcher.Plugin.WebSearch.csproj
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Flow.Launcher.Plugin.WindowsSettings.csproj
  README.md
  Scripts/flowlauncher.nuspec
  Scripts/post_build.ps1
  global.json
Labels: bug, review in progress

#1879 Fix readme typo
  README.md
Labels: bug, Documentation, Dev branch only

#1881 Release version bumps
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#1880 Release 1.13.0 | Plugin 4.0.0
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Test/Flow.Launcher.Test.csproj
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/HotkeyControl.xaml.cs
  Flow.Launcher/Properties/PublishProfiles/Net7.0-SelfContained.pubxml
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingAPI.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchOption.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/Flow.Launcher.Plugin.Url.csproj
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Flow.Launcher.Plugin.WebSearch.csproj
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Flow.Launcher.Plugin.WindowsSettings.csproj
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  README.md
  Scripts/flowlauncher.nuspec
  Scripts/post_build.ps1
  appveyor.yml
  global.json
Labels: release

#1875 [Bookmarks Plugin] Add custom firefox browser support
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/BookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/CustomFirefoxBookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/FirefoxBookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Models/CustomBrowser.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/CustomBrowserSetting.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/CustomBrowserSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/SettingsControl.xaml
Labels: enhancement

#1899 add option for everything search in full path (default true)
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
Labels: bug

#1932 Fix preview hotkey issue
  Flow.Launcher.Infrastructure/Hotkey/HotkeyModel.cs
  Flow.Launcher/HotkeyControl.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#1941 Add sponsor
  README.md
Labels: enhancement, Documentation
