Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2023-12, with the labels that each got.

#2450 Fix spell check
  .github/actions/spelling/expect.txt
  .github/actions/spelling/patterns.txt
  .github/workflows/spelling.yml
Labels: bug, CI/CD

#2431 Show a result error instead of popping up dialog
  Flow.Launcher.Core/Plugin/PluginManager.cs
Labels: enhancement

#2466 README: Add links to plugins
  .github/actions/spelling/expect.txt
  README.md
Labels: Documentation
