Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2023-11, with the labels that each got.

#1353 Implement JSONRPC V2
  Flow.Launcher.Core/ExternalPlugins/Environments/AbstractPluginEnvironment.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/JavaScriptV2Environment.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/PythonV2Environment.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/TypeScriptV2Environment.cs
  Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Plugin/ExecutablePlugin.cs
  Flow.Launcher.Core/Plugin/ExecutablePluginV2.cs
  Flow.Launcher.Core/Plugin/JsonPRCModel.cs
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher.Core/Plugin/JsonRPCPluginBase.cs
  Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
  Flow.Launcher.Core/Plugin/JsonRPCPluginV2.cs
  Flow.Launcher.Core/Plugin/JsonRPCV2Models/JsonRPCExecuteResponse.cs
  Flow.Launcher.Core/Plugin/JsonRPCV2Models/JsonRPCPublicAPI.cs
  Flow.Launcher.Core/Plugin/JsonRPCV2Models/JsonRPCQueryRequest.cs
  Flow.Launcher.Core/Plugin/NodePlugin.cs
  Flow.Launcher.Core/Plugin/NodePluginV2.cs
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
  Flow.Launcher.Core/Plugin/ProcessStreamPluginV2.cs
  Flow.Launcher.Core/Plugin/PythonPlugin.cs
  Flow.Launcher.Core/Plugin/PythonPluginV2.cs
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
  Flow.Launcher.Plugin/AllowedLanguage.cs
  Flow.Launcher.Plugin/Query.cs
  Flow.Launcher.Test/Plugins/JsonRPCPluginTest.cs
Labels: enhancement, review in progress

#2416 switch back to jsonmessageformatter
  Flow.Launcher.Core/Plugin/JsonRPCPluginV2.cs
Labels: Dev branch only

#2415 Use FuzzySearch to search access links
  Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/QuickAccess.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Labels: enhancement, Explorer Plugin, kind/ux

#2369 Delay restart after installing/uninstalling/updating plugins
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Settings.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Views/PluginsManagerSettings.xaml
Labels: enhancement, Code Refactor, kind/ux

#2428 Use ConcurrentDictionary for JsonRPC Settings
  Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
Labels: bug

#2439 Revert "Bump System.Drawing.Common from 7.0.0 to 8.0.0"
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
Labels: bug, Dev branch only

#2418 use memorypack instead of binaryformatter
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Infrastructure/Storage/BinaryStorage.cs
  Flow.Launcher/App.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWPPackage.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
Labels: enhancement

#2432 Ignore modifier key when using key + number to launch result
  Flow.Launcher.Plugin/ActionContext.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#2444 Set default value of `AutoRestartAfterChanging` to `true`
  Plugins/Flow.Launcher.Plugin.PluginsManager/Settings.cs
Labels: Dev branch only
