Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2023-08, with the labels that each got.

#2242 New Crowdin updates
  Flow.Launcher/Languages/cs.xaml
  Flow.Launcher/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.cs-CZ.resx
Labels: bug

#2271 Fix windows search empty paths
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndex.cs
Labels: bug, Explorer Plugin

#2269 Set main Flow Launcher project as default start up
  Flow.Launcher.sln
Labels: bug

#2276 Bump plugin versions
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
Labels: release

#2275 Release 1.16.1 | Plugin 4.1.1
  .github/workflows/winget.yml
  Flow.Launcher.Core/Resource/AvailableLanguages.cs
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Test/Flow.Launcher.Test.csproj
  Flow.Launcher.sln
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Languages/cs.xaml
  Flow.Launcher/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndex.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.cs-CZ.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
Labels: release

#2278 Release 1.16.1 version bump
  appveyor.yml
Labels: release

#2279 Patch release 1.16.1
  appveyor.yml
Labels: release

#2266 Update Python to v3.11.4
  .github/actions/spelling/expect.txt
  Flow.Launcher.Core/ExternalPlugins/Environments/PythonEnvironment.cs
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
Labels: bug

#2295 Publish installable default plugins to Store
  .github/actions/spelling/expect.txt
  .github/workflows/default_plugins.yml
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
Labels: bug
