Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2023-06, with the labels that each got.

#2170 plugin/ProcessKiller: honor "Last Query Style" after kill
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Main.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/ProcessHelper.cs
Labels: enhancement

#2143 Consistent handling of clipboard copying
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#2180 Update AppVeyor NuGet API
  appveyor.yml
Labels: bug

#2123 Reduce CPU and disk usage during Program plugin init
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Settings.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
Labels: bug

#2177 Refactor clipboard copying
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ContextMenuHelper.cs
Labels: bug, Code Refactor

#2174 Improvements for re-queries
  Flow.Launcher.Plugin/Query.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement, kind/ux

#2150 Add quotes surrounding auto startup entry
  Flow.Launcher/Helper/AutoStartup.cs
Labels: bug

#2183 plugin/shell: support Pwsh (PowerShell 7.x)
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
  Plugins/Flow.Launcher.Plugin.Shell/Settings.cs
  Plugins/Flow.Launcher.Plugin.Shell/ShellSetting.xaml
  Plugins/Flow.Launcher.Plugin.Shell/ShellSetting.xaml.cs
Labels: enhancement

#2193 Update Plugin documentation
  Flow.Launcher.Plugin/ActionContext.cs
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Plugin/Interfaces/IContextMenu.cs
  Flow.Launcher.Plugin/Interfaces/IPluginI18n.cs
  Flow.Launcher.Plugin/Interfaces/ISavable.cs
  Flow.Launcher.Plugin/PluginInitContext.cs
  Flow.Launcher.Plugin/Query.cs
  Flow.Launcher.Plugin/README.md
  Flow.Launcher.Plugin/Result.cs
  README.md
Labels: Documentation

#2204 Remove obsolete and unused code
  Deploy/local_build.ps1
  Directory.Build.props
  Flow.Launcher.Core/ExternalPlugins/Environments/AbstractPluginEnvironment.cs
  Flow.Launcher.Core/Plugin/QueryBuilder.cs
  Flow.Launcher.CrashReporter/Flow.Launcher.CrashReporter.csproj
  Flow.Launcher.CrashReporter/Images/app_error.png
  Flow.Launcher.CrashReporter/Images/crash_go.png
  Flow.Launcher.CrashReporter/Images/crash_stop.png
  Flow.Launcher.CrashReporter/Images/crash_warning.png
  Flow.Launcher.CrashReporter/Properties/AssemblyInfo.cs
  Flow.Launcher.CrashReporter/packages.config
  Flow.Launcher.Infrastructure/Storage/ISavable.cs
  Flow.Launcher.Infrastructure/UserSettings/PluginSettings.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher.Plugin/Query.cs
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs
  Flow.Launcher.Test/QueryBuilderTest.cs
  Flow.Launcher.sln
  Flow.Launcher/PublicAPIInstance.cs
Labels: enhancement, Code Refactor

#2199 Added Animation Length slider
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: enhancement

#2152 Fix bookmark plugin file monitoring issue
  .github/actions/spelling/expect.txt
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
Labels: bug, review in progress

#2119 New Crowdin updates
  Flow.Launcher/Languages/da.xaml
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/fr.xaml
  Flow.Launcher/Languages/it.xaml
  Flow.Launcher/Languages/ja.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/nl.xaml
  Flow.Launcher/Languages/pl.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/ru.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/sr.xaml
  Flow.Launcher/Languages/tr.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.sk-SK.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.uk-UA.resx
Labels: bug
