Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2023-09, with the labels that each got.

#2332 Fix exclude path check for index search
  Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
  Flow.Launcher.Test/FilesFoldersTest.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Labels: bug

#2343 Improve hotkey registration failure popup
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/Languages/en.xaml
Labels: kind/ux

#2350 Add explanation for '@' prefix of custom shortcut
  Flow.Launcher/CustomShortcutSetting.xaml
  Flow.Launcher/Images/illustration_02.png
  Flow.Launcher/Languages/en.xaml
Labels: kind/ui, kind/ux

#2330 Release 1.16.2 version bump
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#2331 New Crowdin updates
  Flow.Launcher/Languages/ar.xaml
  Flow.Launcher/Languages/cs.xaml
  Flow.Launcher/Languages/da.xaml
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/fr.xaml
  Flow.Launcher/Languages/it.xaml
  Flow.Launcher/Languages/ja.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/nl.xaml
  Flow.Launcher/Languages/pl.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/ru.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/sr.xaml
  Flow.Launcher/Languages/tr.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.fr-FR.resx
Labels: bug

#2321 Release 1.16.2
  .github/actions/spelling/expect.txt
  .github/workflows/default_plugins.yml
  Flow.Launcher.Core/ExternalPlugins/Environments/PythonEnvironment.cs
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
  Flow.Launcher.Test/FilesFoldersTest.cs
  Flow.Launcher.Test/Flow.Launcher.Test.csproj
  Flow.Launcher/Converters/BoolToVisibilityConverter.cs
  Flow.Launcher/CustomShortcutSetting.xaml
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/Images/illustration_02.png
  Flow.Launcher/Languages/ar.xaml
  Flow.Launcher/Languages/cs.xaml
  Flow.Launcher/Languages/da.xaml
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/fr.xaml
  Flow.Launcher/Languages/it.xaml
  Flow.Launcher/Languages/ja.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/nl.xaml
  Flow.Launcher/Languages/pl.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/ru.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/sr.xaml
  Flow.Launcher/Languages/tr.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/Languages/zh-tw.xaml
  Flow.Launcher/MainWindow.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.fr-FR.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.zh-cn.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  README.md
  appveyor.yml
Labels: release

#2363 Update README's early access link
  README.md
Labels: bug, Documentation

#2365 Fix publish default plugins action not triggering
  .github/workflows/default_plugins.yml
Labels: bug, CI/CD
