Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2023-07, with the labels that each got.

#2211 New Crowdin updates
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/Msg.xaml.cs
Labels: bug

#2216 Add Plugin API -> VisibilityChangedEventHandler
  Flow.Launcher.Plugin/EventHandler.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#2222 Rework how we fetch community plugin data
  Flow.Launcher.Core/ExternalPlugins/CommunityPluginSource.cs
  Flow.Launcher.Core/ExternalPlugins/CommunityPluginStore.cs
  Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
Labels: enhancement, kind/ux

#2231 Switch winget release action to manual
  .github/workflows/winget.yml
Labels: bug, CI/CD, github_actions

#2230 New Crowdin updates
  Flow.Launcher/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.cs-CZ.resx
Labels: bug

#2209 Bump versions for release
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#2239 Fix name of Slovak language
  Flow.Launcher.Core/Resource/AvailableLanguages.cs
Labels: bug
