Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2024-05, with the labels that each got.

#2685 Improve readme
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  README.md
Labels: Documentation

#2687 Fix README.md typo
  README.md
Labels: Dev branch only

#2697 Block Mouse Hover event when Show / Keyboard Navigation
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug

#2520 Feature: Add support for local plugin installation
  Flow.Launcher.Core/ExternalPlugins/UserPlugin.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Images/zipfolder.png
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Utilities.cs
Labels: enhancement

#2696 Ported "Up Arrow key cycles through Query history" PR
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#2677 Fix SettingWindow's LeftTop Position when first launch
  Flow.Launcher/SettingWindow.xaml.cs
Labels: bug

#2674 Code separation in the settings window
  Flow.Launcher/App.xaml
  Flow.Launcher/CustomShortcutSetting.xaml.cs
  Flow.Launcher/Images/info.png
  Flow.Launcher/Images/keyboard.png
  Flow.Launcher/Images/plugins.png
  Flow.Launcher/Images/proxy.png
  Flow.Launcher/Images/store.png
  Flow.Launcher/Images/theme.png
  Flow.Launcher/Resources/Controls/Card.xaml
  Flow.Launcher/Resources/Controls/Card.xaml.cs
  Flow.Launcher/Resources/Controls/CardGroup.xaml
  Flow.Launcher/Resources/Controls/CardGroup.xaml.cs
  Flow.Launcher/Resources/Controls/CardGroupCardStyleSelector.cs
  Flow.Launcher/Resources/Controls/HyperLink.xaml
  Flow.Launcher/Resources/Controls/HyperLink.xaml.cs
  Flow.Launcher/Resources/Controls/InstalledPluginDisplay.xaml
  Flow.Launcher/Resources/Controls/InstalledPluginDisplay.xaml.cs
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/Resources/MarkupExtensions/CollapsedWhenExtension.cs
  Flow.Launcher/Resources/MarkupExtensions/HideableVisibilityConverter.cs
  Flow.Launcher/Resources/MarkupExtensions/VisibleWhenExtension.cs
  Flow.Launcher/Resources/SettingWindowStyle.xaml
  Flow.Launcher/SettingPages/ViewModels/DropdownDataGeneric.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneHotkeyViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginStoreViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginsViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneProxyViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneHotkey.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneHotkey.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml
  Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml
  Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneProxy.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneProxy.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/PluginStoreItemViewModel.cs
  Flow.Launcher/ViewModel/PluginViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: kind/ui, Code Refactor

#2683 Add Windows Media Player Warning
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Helper/WindowsMediaPlayerHelper.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
Labels: bug, kind/ui

#2679 Improve Explorer Preview Panel
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/PreviewPanel.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/PreviewPanel.xaml.cs
Labels: kind/ux

#2720 Update wording
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
Labels: Dev branch only

#2722 Fix bug and typo in Calculator Plugin
  Flow.Launcher.Core/Resource/Internationalization.cs
  Flow.Launcher/Converters/QuerySuggestionBoxConverter.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.Calculator/DecimalSeparator.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
  Plugins/Flow.Launcher.Plugin.Calculator/NumberTranslator.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Settings.cs
  Plugins/Flow.Launcher.Plugin.Calculator/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Views/CalculatorSettings.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Views/CalculatorSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
Labels: bug

#2724 Remove Vietnamese resource file
  Flow.Launcher/Properties/Resources.vi-VN.resx
Labels: Dev branch only

#2726 Program plugin: add option to hide uninstallers from results
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Settings.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
Labels: enhancement

#2700 add a close overload for jsonrpcpluginv2
  Flow.Launcher.Core/Plugin/JsonRPCPluginV2.cs
Labels: bug

#2732 Real-time updates to ComboBox localization in general pane of settings after changing the language
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/ru.xaml
  Flow.Launcher/SettingPages/ViewModels/DropdownDataGeneric.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
Labels: bug, kind/i18n

#2699 Resizable Window + Customize
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/Resources/Dark.xaml
  Flow.Launcher/Resources/Light.xaml
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
Labels: enhancement

#2733 Fix Saving Window Width
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#2727 Fix startup error message when not able to register hotkey being English-only
  Flow.Launcher/App.xaml.cs
Labels: bug, kind/i18n

#2740 Change Caching Policy
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/Image/ImageCache.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
Labels: bug
