Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2024-04, with the labels that each got.

#2627 Fix typo
  Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
Labels: bug, Dev branch only

#2636 Show target path in hover tooltip
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Labels: enhancement

#2654 Bump Version 1.18.0
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#2663 Add Vietnamese Support
  .github/actions/spelling/expect.txt
  Flow.Launcher.Core/Resource/AvailableLanguages.cs
Labels: bug, kind/i18n

#2664 Support Screen Reader
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml
Labels: bug, kind/ux

#2665 Change shellexecute for command without argument
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
Labels: bug, Dev branch only

#2648 Improve Hotkey System
  Flow.Launcher.Infrastructure/Hotkey/HotkeyModel.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
  Flow.Launcher/HotkeyControl.xaml
  Flow.Launcher/HotkeyControl.xaml.cs
  Flow.Launcher/HotkeyControlDialog.xaml
  Flow.Launcher/HotkeyControlDialog.xaml.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/Resources/Controls/Card.xaml
  Flow.Launcher/Resources/Controls/Card.xaml.cs
  Flow.Launcher/Resources/Controls/ExCard.xaml
  Flow.Launcher/Resources/Controls/ExCard.xaml.cs
  Flow.Launcher/Resources/Controls/HotkeyDisplay.xaml
  Flow.Launcher/Resources/Controls/HotkeyDisplay.xaml.cs
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/Resources/Dark.xaml
  Flow.Launcher/Resources/Light.xaml
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage3.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
  Flow.Launcher/WelcomeWindow.xaml
Labels: enhancement, kind/ui, kind/ux

#2669 Fix Icon Position in PREV/NEXT page hotkey
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingWindow.xaml
Labels: bug, Dev branch only

#2667 Handle duplicate hotkeys in HotkeyControlDialog
  Flow.Launcher.Infrastructure/Hotkey/IHotkeySettings.cs
  Flow.Launcher.Infrastructure/Hotkey/RegisteredHotkeyData.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
  Flow.Launcher/HotkeyControl.xaml.cs
  Flow.Launcher/HotkeyControlDialog.xaml
  Flow.Launcher/HotkeyControlDialog.xaml.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml
  Flow.Launcher/SettingWindow.xaml
Labels: kind/ux
