Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2024-02, with the labels that each got.

#2521 Remove redundant wording
  README.md
Labels: Documentation

#2510 New Crowdin updates
  Flow.Launcher/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.fr-FR.resx
Labels: bug

#2457 add a safety check for getproperty
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
Labels: bug

#2524 Bump versions for release 1.17.0
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#2525 Add sponsor to README
  README.md
Labels: enhancement

#2533 Fix: Explorer plugin's Windows Index search returning no results
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndex.cs
Labels: bug

#2527 Prepend actionkeyword to suggestions
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug

#2528 Prepend clipboard to query
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug

#2537 Release version bumps
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  appveyor.yml
Labels: release

#2536 Release 1.17.1
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndex.cs
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  appveyor.yml
Labels: release

#2549 Job Object to kill child processes
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Plugin/ProcessStreamPluginV2.cs
Labels: bug

#2559 Remove short circuit check for empty Settings
  Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
Labels: bug

#2557 Fix Nodejs plugins not working
  Flow.Launcher.Core/Plugin/NodePlugin.cs
Labels: bug, High Priority

#2544 New Crowdin updates
  Plugins/Flow.Launcher.Plugin.Sys/Languages/de.xaml
Labels: bug

#2564 Bump versions for 1.17.2
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  appveyor.yml
Labels: release

#2563 Release 1.17.2
  Flow.Launcher.Core/ExternalPlugins/CommunityPluginSource.cs
  Flow.Launcher.Core/ExternalPlugins/UserPlugin.cs
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
  Flow.Launcher.Core/Plugin/NodePlugin.cs
  Flow.Launcher.Core/Plugin/ProcessStreamPluginV2.cs
  Plugins/Flow.Launcher.Plugin.Sys/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Settings.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/DuckDuckGo.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  appveyor.yml
Labels: release

#2566 New Crowdin updates
  Flow.Launcher/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.fr-FR.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.zh-cn.resx
Labels: bug
