Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2024-07, with the labels that each got.

#2811 Fix Preview Panel Separator
  Plugins/Flow.Launcher.Plugin.Explorer/Views/PreviewPanel.xaml
Labels: Dev branch only, 1 min review

#2803 Support QTTabBar
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/SelectFileManagerWindow.xaml
Labels: bug, 1 min review

#2823 Remove cm percent new code automation & ignore specific branches
  .cm/gitstream.cm
Labels: Dev branch only, cm-changes

#2822 Revert "Fix Window Positioning with Multiple Montiors"
  Flow.Launcher.Infrastructure/UserSettings/Point2D.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, 5 min review

#2834 Fix partial env variable path search
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Labels: bug, 1 min review

#2837 Fix gitStream image request regex
  .cm/gitstream.cm
Labels: Dev branch only, cm-changes

#2836 feat: Everything Run Count option
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchOption.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
Labels: enhancement, Explorer Plugin, everything

#2769 Localize startup messages about missing Python/NodeJS
  Flow.Launcher.Core/ExternalPlugins/Environments/AbstractPluginEnvironment.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Resource/Internationalization.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Languages/ru.xaml
Labels: bug, enhancement, kind/i18n, Code Refactor, 1 min review

#2842 feat: Exclude certain File Types from the Index search result
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
Labels: enhancement, Explorer Plugin, 1 min review
