Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2024-06, with the labels that each got.

#2748 Small Fix in Setting window
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/Resources/Dark.xaml
  Flow.Launcher/Resources/Light.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
  Flow.Launcher/SettingWindow.xaml
Labels: bug, kind/ui

#2751 Don't re-run queries after returning from context menu
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, kind/ux

#2752 Change App Error icon
  Flow.Launcher/Images/app_error.png
Labels: kind/ui, Small PR

#2755 DPI per Monitor
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/app.manifest
Labels: bug, Small PR

#2757 fix process exited before calling "close" method on dispose.
  Flow.Launcher.Core/Plugin/ProcessStreamPluginV2.cs
Labels: bug, Dev branch only

#2735 Adjust Themes
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/App.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/Resources/Dark.xaml
  Flow.Launcher/Resources/Light.xaml
  Flow.Launcher/Resources/SettingWindowStyle.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/BlurBlack Darker.xaml
  Flow.Launcher/Themes/BlurBlack.xaml
  Flow.Launcher/Themes/BlurWhite.xaml
  Flow.Launcher/Themes/Bullet Light.xaml
  Flow.Launcher/Themes/Circle Light.xaml
  Flow.Launcher/Themes/Circle System.xaml
  Flow.Launcher/Themes/Cyan Dark.xaml
  Flow.Launcher/Themes/Darker Glass.xaml
  Flow.Launcher/Themes/Discord Dark.xaml
  Flow.Launcher/Themes/Dracula.xaml
  Flow.Launcher/Themes/Gray.xaml
  Flow.Launcher/Themes/League.xaml
  Flow.Launcher/Themes/Nord Darker.xaml
  Flow.Launcher/Themes/Pink.xaml
  Flow.Launcher/Themes/SlimLight.xaml
  Flow.Launcher/Themes/Sublime.xaml
  Flow.Launcher/Themes/Ubuntu.xaml
  Flow.Launcher/Themes/Win10Light.xaml
  Flow.Launcher/Themes/Win10System.xaml
  Flow.Launcher/Themes/Win11Dark.xaml
  Flow.Launcher/Themes/Win11Light.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/PreviewPanel.xaml
Labels: kind/ui

#2765 Fix Plugin Manager Setting Panel
  Plugins/Flow.Launcher.Plugin.PluginsManager/Views/PluginsManagerSettings.xaml
Labels: kind/ui, Small PR

#2749 Use binding for values introduced in Resizable PR
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml.cs
Labels: Code Refactor, Dev branch only

#2767 Fix "always preview" card subtitle not displaying the hotkey in Settings — General
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
Labels: bug, Small PR

#2770 Add gitStream workflow
  .cm/gitstream.cm
  .github/workflows/gitstream.yml
Labels: enhancement, CI/CD

#2772 Update AppVeyor NuGet API
  appveyor.yml
Labels: bug, 1 min review, no-screenshot

#2773 Remove no-screenshot labelling from gitStream
  .cm/gitstream.cm
Labels: Dev branch only, cm-changes

#2774 Add MessageBoxEx
  Flow.Launcher/Images/Error.png
  Flow.Launcher/Images/Exclamation.png
  Flow.Launcher/Images/Information.png
  Flow.Launcher/Images/Question.png
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MessageBoxEx.xaml
  Flow.Launcher/MessageBoxEx.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
Labels: enhancement, 20 min review

#2763 Explorer plugin: open native context menu on Alt+Enter press
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneHotkey.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
Labels: enhancement, Explorer Plugin, kind/ux, 5 min review

#2082 Add external preview (QuickLook) support
  .github/actions/spelling/expect.txt
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Plugin/Interfaces/IAsyncExternalPreview.cs
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
Labels: enhancement

#2783 Add auto assign PR assignee
  .github/workflows/pr_assignee.yml
Labels: enhancement, CI/CD, 1 min review

#2784 Add auto assign milestone GitHub action
  .cm/gitstream.cm
  .github/workflows/pr_milestone.yml
Labels: enhancement, CI/CD, cm-changes

#2789 Add new PR Labeler app configuration file
  .github/pr-labeler.yml
Labels: 1 min review

#2742 Integrate native Windows context menu directly into the Explorer plugin
  Flow.Launcher/ResultListBox.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Helper/ShellContextMenuDisplayHelper.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
Labels: bug, enhancement, Explorer Plugin, 30 min review

#2793 Fix Win11 Theme's Right Margin
  Flow.Launcher/Themes/Win11Light.xaml
Labels: bug, 1 min review

#2796 Settings: fix creating/editing custom shortcuts
  Flow.Launcher/CustomShortcutSetting.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneHotkeyViewModel.cs
Labels: bug, Dev branch only, 1 min review

#2756 Fix Window Positioning with Multiple Montiors
  Flow.Launcher.Infrastructure/UserSettings/Point2D.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, enhancement, 10 min review

#2808 Modify gitStream todo checks
  .cm/gitstream.cm
Labels: bug, cm-changes

#2795 New Crowdin updates
  Flow.Launcher/Languages/fr.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.vi-VN.resx
Labels: bug, enhancement, kind/i18n, 5 min review

#2810 Add Sponsor in Readme.Md
  README.md
Labels: enhancement, 1 min review
