Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2024-10, with the labels that each got.

#2997 New Crowdin updates
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.de-DE.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.nb-NO.resx
Labels: bug, kind/i18n

#3032 Release 1.19.3 version bumps
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#3033 Null check when detecting Windows Media Player installation
  Flow.Launcher/Helper/WindowsMediaPlayerHelper.cs
Labels: bug

#3029 New Crowdin updates
  Flow.Launcher/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.de-DE.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.nb-NO.resx
Labels: bug, kind/i18n

#3027 Release 1.19.3
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Helper/WindowsMediaPlayerHelper.cs
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Program/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.de-DE.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.nb-NO.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#3054 fix out of index error when install source is not standard github link
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
Labels: bug, 1 min review
