Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2024-08, with the labels that each got.

#2881 Fix startup localization issues
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Resource/Internationalization.cs
Labels: Dev branch only, 1 min review

#2885 Add sponsor
  README.md
Labels: enhancement, 1 min review

#2883 Fix ClockText and DateText to use CurrentUICulture
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
Labels: bug, 1 min review

#2874 Pass MaxResult setting to EverythingApi
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
Labels: bug, 1 min review

#2888 Version bumps for release 1.19.0
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release, 5 min review

#2817 New Crowdin updates
  Flow.Launcher/Languages/ar.xaml
  Flow.Launcher/Languages/cs.xaml
  Flow.Launcher/Languages/da.xaml
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/fr.xaml
  Flow.Launcher/Languages/it.xaml
  Flow.Launcher/Languages/ja.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/nl.xaml
  Flow.Launcher/Languages/pl.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/ru.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/sr.xaml
  Flow.Launcher/Languages/tr.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/vi.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.ar-SA.resx
Labels: bug, kind/i18n

#2889 New Crowdin updates
  Flow.Launcher/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/sk.xaml
Labels: bug, kind/i18n

#2918 Add "Enabled" Column in Customize Action Keyword Tab
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
Labels: kind/ui, Explorer Plugin, 1 min review

#2921 Create Top-Ranking Issues workflow
  .github/workflows/top-ranking-issues.yml
Labels: bug, enhancement, CI/CD, 1 min review

#2934 Fix Node.js path select error in settings window
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
Labels: bug, 1 min review

#2903 New Crowdin updates
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.zh-cn.resx
Labels: bug, kind/i18n
