Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2024-12, with the labels that each got.

#3104 Return data uri image as icon support
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Plugin/Result.cs
Labels: enhancement

#3099 Fix possible null reference when query is cancelled & Add new image icon for images whose formats are not support & Other improvements
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher/Images/image.png
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/Storage/TopMostRecord.cs
  Flow.Launcher/Storage/UserSelectedRecord.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, enhancement, 1 min review

#3093 Replace original MessageBox with MessageBoxEx & Improve MessageBoxEx display style & Add new public api for using MessageBoxEx
  Flow.Launcher.Core/Configuration/Portable.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/AbstractPluginEnvironment.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/PythonEnvironment.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/TypeScriptEnvironment.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/TypeScriptV2Environment.cs
  Flow.Launcher.Core/MessageBoxEx.xaml
  Flow.Launcher.Core/MessageBoxEx.xaml.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
  Flow.Launcher.Core/Resource/Internationalization.cs
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher.Core/Updater.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
  Flow.Launcher/ActionKeywords.xaml.cs
  Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
  Flow.Launcher/CustomShortcutSetting.xaml.cs
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/Images/warning.png
  Flow.Launcher/MessageBoxEx.xaml.cs
  Flow.Launcher/PriorityChangeWindow.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneHotkeyViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneProxyViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingDownloadHelper.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.Program/AddProgramSource.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/ProgramSuffixes.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceViewModel.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml.cs
Labels: enhancement

#3082 [WebSearch] Add copy URL to menu
  Plugins/Flow.Launcher.Plugin.WebSearch/Images/copylink.png
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
Labels: enhancement

#3087 Add new public api function BackToQueryResults for chaning the query list back to query results list
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#3114 add CopyText and AutoCompleteText to some results in the sys plugin
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
Labels: 1 min review

#3119 Improve windows index search with special character
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/QueryConstructor.cs
Labels: bug

#3131 Add more date formats in settings
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
Labels: enhancement

#3117 ci: fix permissions + migrate to fresher action (Pr Assign)
  .github/workflows/pr_assignee.yml
  .github/workflows/pr_milestone.yml
Labels: bug, CI/CD

#3118 Add preserve last action keyword options
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#3144 Add options for setting result on top & keeping result order
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#3115 Fix possible result update issue for plugins with IResultUpdate interface
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, 1 min review

#3122 Replace DllImport and flags with CSWin32 & Remove useless DllImport and flags & Fix right Win key click issue
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher.Infrastructure/FileExplorerHelper.cs
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/Hotkey/GlobalHotkey.cs
  Flow.Launcher.Infrastructure/Hotkey/InterceptKeys.cs
  Flow.Launcher.Infrastructure/Hotkey/KeyEvent.cs
  Flow.Launcher.Infrastructure/Image/ThumbnailReader.cs
  Flow.Launcher.Infrastructure/NativeMethods.txt
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Infrastructure/Win32Helper.cs
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Plugin/NativeMethods.txt
  Flow.Launcher.Plugin/SharedCommands/ShellCommand.cs
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Helper/DWMDropShadow.cs
  Flow.Launcher/Helper/SingleInstance.cs
  Flow.Launcher/Helper/WallpaperPathRetrieval.cs
  Flow.Launcher/Helper/WindowsInteropHelper.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/NativeMethods.txt
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/NativeMethods.txt
  Plugins/Flow.Launcher.Plugin.ProcessKiller/ProcessHelper.cs
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Program/NativeMethods.txt
  Plugins/Flow.Launcher.Plugin.Program/Programs/ShellLinkHelper.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/ShellLocalization.cs
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.Sys/NativeMethods.txt
Labels: bug
