Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2024-09, with the labels that each got.

#2949 New Crowdin updates
  Flow.Launcher/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/de.xaml
Labels: bug, kind/i18n

#2958 fix grammar
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
Labels: bug

#2955 Release version bumps
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release, 5 min review

#2954 Release 1.19.1
  .github/workflows/default_plugins.yml
  .github/workflows/top-ranking-issues.yml
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Test/Flow.Launcher.Test.csproj
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.zh-cn.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#2960 Update gitstream.cm minutes to review trigger rule
  .cm/gitstream.cm
Labels: bug, CI/CD, cm-changes

#2983 Fix Multiple Display different DPI causing weird staring position
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug

#2959 New Crowdin updates
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.pl-PL.resx
Labels: bug, kind/i18n

#2990 Version bump for release 1.19.2
  appveyor.yml
Labels: release

#2991 Release 1.19.2
  .cm/gitstream.cm
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Test/Flow.Launcher.Test.csproj
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/pl.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.pl-PL.resx
  appveyor.yml
Labels: release
