Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2024-11, with the labels that each got.

#3057 Fix `inputWithFileBtn` not working in SettingsTemplate.yml
  Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
Labels: bug, enhancement

#3034 New Crowdin updates
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Url/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.de-DE.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.nb-NO.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.pt-PT.resx
Labels: bug, kind/i18n

#3060 Version bump 1.19.4 release
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#3059 Release 1.19.4
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.de-DE.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.nb-NO.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.pt-PT.resx
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: release

#3064 Add sponsor to readme
  README.md
Labels: bug, Documentation

#3069 Fix Style for Highcontrast mode
  Flow.Launcher/App.xaml
Labels: bug

#3086 Suggest fix regex in gitstream CM file
  .cm/gitstream.cm
Labels: bug, cm-changes

#3092 Fix System.OperationCanceledException Issue
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
Labels: bug

#3088 Fix possible content frame navigation issue in welcome window & setting window
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/WelcomeWindow.xaml
  Flow.Launcher/WelcomeWindow.xaml.cs
Labels: bug, 1 min review
