Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2024-01, with the labels that each got.

#2481 Add ToggleGameMode to system commands
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  README.md
Labels: enhancement

#2475 Update system commands in README
  README.md
Labels: bug, Documentation

#2412 feat: Update all plugins result
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
Labels: enhancement

#2500 Update stale workflow
  .github/workflows/stale.yml
Labels: enhancement

#2506 Speed up context menu search
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#2482 [no ci] README: fix appwrite logo, md improvements
  README.md
Labels: Documentation
