Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2025-01, with the labels that each got.

#3165 Fix Copy Action Issue
  Flow.Launcher.Infrastructure/NativeMethods.txt
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Infrastructure/Win32Helper.cs
  Flow.Launcher/PublicAPIInstance.cs
Labels: Dev branch only

#3168 Fix operator equal application issue
  Flow.Launcher.Infrastructure/FileExplorerHelper.cs
Labels: 1 min review

#3149 New Crowdin updates
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/he.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/he.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.de-DE.resx
Labels: bug, kind/i18n

#3174 Use System.Text.Json to replace Newtonsoft.Json for better performance
  Plugins/Flow.Launcher.Plugin.PluginsManager/Utilities.cs
Labels: 1 min review

#3112 Remove Result Equal used for WPF caching
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher.Test/Plugins/JsonRPCPluginTest.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
Labels: bug

#3197 Improve uninstaller check function
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
Labels: bug

#3161 Add System Language Item
  Flow.Launcher.Core/Resource/AvailableLanguages.cs
  Flow.Launcher.Core/Resource/Internationalization.cs
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
Labels: enhancement

#3190 do not try catch the error for jsonrpc v2
  Flow.Launcher.Core/Plugin/JsonRPCPluginV2.cs
Labels: bug

#3204 Fix setting window freeze issue & Improve singleton window opener
  Flow.Launcher/Helper/SingletonWindowOpener.cs
  Flow.Launcher/SettingWindow.xaml.cs
Labels: bug

#3206 Merge release 1.19.5 back into dev branch
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: Dev branch only
