Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2025-03, with the labels that each got.

#3294 Add loading bar api functions for all plugins
  Flow.Launcher.Core/Plugin/JsonRPCV2Models/JsonRPCPublicAPI.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
Labels: 1 min review

#3300 Remove unneccessary CreateSettingPanel by introducing need check
  Flow.Launcher.Core/Plugin/JsonRPCPluginBase.cs
  Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
  Flow.Launcher/ViewModel/PluginViewModel.cs
Labels: enhancement

#3306 Fix null reference exception when checking source
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
Labels: bug

#3313 Use official Task Scheduler
  Flow.Launcher/Flow.Launcher.csproj
Labels: Small PR

#3320 Add new sponsor to README
  README.md
Labels: enhancement, 1 min review

#3317 Update dependabot.yml
  .github/dependabot.yml
Labels: Small PR

#3328 Revert "Bump System.Data.OleDb from 8.0.1 to 9.0.2"
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
Labels: Dev branch only

#2739 Allow log level selection
  Flow.Launcher.Infrastructure/Logger/Log.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
Labels: no-pr-activity, 5 min review

#3342 Move log level to about page
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
Labels: 1 min review

#3310 Fix Welcome Backspace Issue & Fix Hotkey Control Settings Null Exception
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/HotkeyControl.xaml.cs
  Flow.Launcher/HotkeyControlDialog.xaml.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage1.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage3.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage4.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage5.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneHotkey.xaml
  Flow.Launcher/ViewModel/WelcomeViewModel.cs
  Flow.Launcher/WelcomeWindow.xaml
  Flow.Launcher/WelcomeWindow.xaml.cs
Labels: bug

#3349 Update all Fody dependencies to Fody 6.5.5
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher/Flow.Launcher.csproj
Labels: bug

#3311 Use dependency injection instead of navigation parameter
  Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneHotkey.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneProxy.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml.cs
  Flow.Launcher/SettingWindow.xaml.cs
Labels: enhancement, Code Quality

#1445 Fixed Progressbar Dispatcher Exception
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug, 1 min review

#3354 Fix custom query hotkey settings issue
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/HotkeyControl.xaml.cs
Labels: Dev branch only, 1 min review

#3357 Fix hotkey initialization issue
  Flow.Launcher/HotkeyControl.xaml.cs
Labels: bug, Dev branch only

#3271 Fluent Window
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher.Infrastructure/MonitorInfo.cs
  Flow.Launcher.Infrastructure/NativeMethods.txt
  Flow.Launcher.Infrastructure/PInvokeExtensions.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Infrastructure/Win32Helper.cs
  Flow.Launcher/App.xaml
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Helper/DWMDropShadow.cs
  Flow.Launcher/Helper/WallpaperPathRetrieval.cs
  Flow.Launcher/Helper/WindowsInteropHelper.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Msg.xaml.cs
  Flow.Launcher/NativeMethods.txt
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/Resources/Dark.xaml
  Flow.Launcher/Resources/Light.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml.cs
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/BlurBlack Darker.xaml
  Flow.Launcher/Themes/BlurBlack.xaml
  Flow.Launcher/Themes/BlurWhite.xaml
  Flow.Launcher/Themes/Circle System.xaml
  Flow.Launcher/Themes/Darker.xaml
  Flow.Launcher/Themes/Pink.xaml
  Flow.Launcher/Themes/Ubuntu.xaml
  Flow.Launcher/Themes/Win10System.xaml
  Flow.Launcher/Themes/Win11Light.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.Sys/ThemeSelector.cs
Labels: bug, enhancement, kind/ui, 30 min review

#3362 Fix #3292
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
Labels: bug, 1 min review

#3369 Enable acrylic effect on first launch
  Flow.Launcher/MainWindow.xaml.cs
Labels: kind/ux, 1 min review

#3365 Fix Plugin Manager Issue
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, Dev branch only

#3374 Fix cursor doesn't move to the end on initial launch
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug, 1 min review

#3366 Implement auto-switching to English when the option is enabled
  Flow.Launcher.Infrastructure/NativeMethods.txt
  Flow.Launcher.Infrastructure/Win32Helper.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, enhancement

#3376 Fix Language Change Issue
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Resource/Internationalization.cs
  Flow.Launcher/App.xaml.cs
Labels: Dev branch only

#3367 Graceful shutdown
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Helper/SingleInstance.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, enhancement, 20 min review

#3377 Fix font select function
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/BlurBlack Darker.xaml
Labels: Dev branch only, 20 min review

#3370 Support Preview Panel for History Results
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
Labels: enhancement, kind/ui

#3150 Put Processes with Visible Window On the Top & Do not kill FL Process
  Flow.Launcher.Infrastructure/FileExplorerHelper.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Views/PluginsManagerSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Main.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/NativeMethods.txt
  Plugins/Flow.Launcher.Plugin.ProcessKiller/ProcessHelper.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/ProcessResult.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Settings.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Views/SettingsControl.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Views/SettingsControl.xaml.cs
Labels: enhancement, 5 min review

#3387 Back to original action for UX
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Main.cs
Labels: Dev branch only

#3388 Fix Clock/Search Icon show logic
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Resources/Dark.xaml
  Flow.Launcher/Resources/Light.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, kind/ui, Dev branch only, 10 min review

#3389 Task delay: Beyond Journey's End
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: Dev branch only

#3391 Fix first-time window flicker & clock panel flicker issue
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: Dev branch only

#3392 Fix application null exception & Remove unused MainWindowOpacity property
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: Dev branch only, 1 min review

#3396 Support Placeholder Text & Toggle Resize Mode
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher.Core/Resource/ThemeManager.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
  Flow.Launcher/Themes/Discord Dark.xaml
  Flow.Launcher/Themes/League.xaml
  Flow.Launcher/Themes/Pink.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#3395 Add glyph icons for Sys Plugin
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
Labels: kind/ui

#3398 Fix Preview in Welcome Window & Wallpaper Retriever Improvement
  Flow.Launcher/Helper/WallpaperPathRetrieval.cs
  Flow.Launcher/Resources/Pages/WelcomePage1.xaml
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml
  Flow.Launcher/Resources/Pages/WelcomePage5.xaml
Labels: Dev branch only

#3272 Improve Plugin Metadata & Path Management
  Flow.Launcher.Core/ExternalPlugins/Environments/AbstractPluginEnvironment.cs
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher.Core/Plugin/JsonRPCPluginBase.cs
  Flow.Launcher.Core/Plugin/PluginConfig.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
  Flow.Launcher.Infrastructure/Constant.cs
  Flow.Launcher.Infrastructure/Logger/Log.cs
  Flow.Launcher.Infrastructure/Storage/BinaryStorage.cs
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
  Flow.Launcher.Infrastructure/Storage/PluginJsonStorage.cs
  Flow.Launcher.Infrastructure/UserSettings/DataLocation.cs
  Flow.Launcher.Infrastructure/UserSettings/PluginSettings.cs
  Flow.Launcher.Plugin/ActionContext.cs
  Flow.Launcher.Plugin/Interfaces/IResultUpdated.cs
  Flow.Launcher.Plugin/Interfaces/ISettingProvider.cs
  Flow.Launcher.Plugin/PluginInitContext.cs
  Flow.Launcher.Plugin/PluginMetadata.cs
  Flow.Launcher.Plugin/PluginPair.cs
  Flow.Launcher.Plugin/Query.cs
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs
  Flow.Launcher.Plugin/SharedCommands/ShellCommand.cs
  Flow.Launcher.Plugin/SharedModels/MatchResult.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
Labels: bug, enhancement, Documentation, Dev branch only

#3394 Adjust Hotkey Design
  Flow.Launcher/Resources/Dark.xaml
  Flow.Launcher/Resources/Light.xaml
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/BlurBlack Darker.xaml
  Flow.Launcher/Themes/BlurBlack.xaml
  Flow.Launcher/Themes/BlurWhite.xaml
  Flow.Launcher/Themes/Circle System.xaml
  Flow.Launcher/Themes/Cyan Dark.xaml
  Flow.Launcher/Themes/Darker Glass.xaml
  Flow.Launcher/Themes/Discord Dark.xaml
  Flow.Launcher/Themes/Dracula.xaml
  Flow.Launcher/Themes/League.xaml
  Flow.Launcher/Themes/Midnight.xaml
  Flow.Launcher/Themes/Nord Darker.xaml
  Flow.Launcher/Themes/Pink.xaml
  Flow.Launcher/Themes/SlimLight.xaml
  Flow.Launcher/Themes/Sublime.xaml
  Flow.Launcher/Themes/Ubuntu.xaml
  Flow.Launcher/Themes/Win10System.xaml
  Flow.Launcher/Themes/Win11Light.xaml
Labels: 10 min review

#3401 Fix Application.Current null exception
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: Dev branch only

#3350 Input Smooth & Search delay
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
  Flow.Launcher.Infrastructure/UserSettings/PluginSettings.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Plugin/PluginMetadata.cs
  Flow.Launcher.Plugin/SearchDelayTime.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Resources/Controls/InstalledPluginDisplay.xaml
  Flow.Launcher/Resources/Controls/InstalledPluginSearchDelay.xaml
  Flow.Launcher/Resources/Controls/InstalledPluginSearchDelay.xaml.cs
  Flow.Launcher/SearchDelayTimeWindow.xaml
  Flow.Launcher/SearchDelayTimeWindow.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/DropdownDataGeneric.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginsViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/PluginViewModel.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
Labels: bug, enhancement, Documentation, 10 min review

#3405 Remove search delay debug codes
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: Dev branch only

#3400 Organizing the settings page
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Resources/Controls/Card.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
Labels: bug, enhancement, kind/ui, 5 min review
