Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2025-07, with the labels that each got.

#3791 Check if plugin is modified before querying
  Flow.Launcher.Core/Plugin/PluginManager.cs
Labels: bug

#3797 Add Theme mode API Function
  Flow.Launcher.Plugin/EventHandler.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#3796 Return results when query is empty for Program
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWPPackage.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Labels: enhancement

#3798 Enable dark mode if the system is in dark mode for Win32 windows
  Flow.Launcher.Infrastructure/Win32Helper.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
Labels: enhancement

#3802 Remove plugins from global & non-global plugins when they are removed from settings
  Flow.Launcher.Core/Plugin/PluginManager.cs
Labels: bug, 1 min review

#3805 Use System.Version to compare versions
  Flow.Launcher.Core/Plugin/PluginManager.cs
Labels: bug

#3811 Update home page when language changes
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug, kind/ui

#3803 Refactor CustomQueryHotkeySetting control
  Flow.Launcher.Infrastructure/UserSettings/PluginHotkey.cs
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
  Flow.Launcher/CustomShortcutSetting.xaml.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneHotkeyViewModel.cs
Labels: enhancement, Code Refactor

#3810 Fix Quick Access Link Type Fetching Issue
  Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/QuickAccessLinkSettings.xaml.cs
Labels: bug

#3816 Use try-catch for query text box paste
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug

#3806 Generate documents for NuGet package
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
Labels: enhancement

#3758 release_pr GitHub workflow automatically get milestone from release PR
  .github/update_release_pr.py
Labels: bug, CI/CD

#3807 New Crowdin updates
  Flow.Launcher/Languages/ar.xaml
  Flow.Launcher/Languages/cs.xaml
  Flow.Launcher/Languages/da.xaml
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/fr.xaml
  Flow.Launcher/Languages/he.xaml
  Flow.Launcher/Languages/it.xaml
  Flow.Launcher/Languages/ja.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/nl.xaml
  Flow.Launcher/Languages/pl.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/ru.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/sr.xaml
  Flow.Launcher/Languages/tr.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/vi.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/he.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.WebSearch/Languages/uk-UA.xaml
Labels: bug, kind/i18n

#3821 Fix the issue that UWP changes that can't be monitored (#2345)
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWPPackage.cs
Labels: bug

#2427 Double pinyin query
  Flow.Launcher.Infrastructure/IAlphabet.cs
  Flow.Launcher.Infrastructure/PinyinAlphabet.cs
  Flow.Launcher.Infrastructure/StringMatcher.cs
  Flow.Launcher.Infrastructure/TranslationMapping.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Test/TranslationMappingTest.cs
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Resources/double_pinyin.json
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
Labels: enhancement, Code Refactor

#3825 Improve performance and readablility of Pinyin Alphabet
  .github/actions/spelling/expect.txt
  Flow.Launcher.Infrastructure/PinyinAlphabet.cs
  Flow.Launcher.Infrastructure/TranslationMapping.cs
  Flow.Launcher.Test/TranslationMappingTest.cs
Labels: bug, enhancement, Code Refactor, Dev branch only, 10 min review

#3830 Reload on all settings change
  Flow.Launcher.Infrastructure/PinyinAlphabet.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
Labels: Dev branch only

#3827 Add Support for Automatically Checking Plugin Updates
  Flow.Launcher.Core/Plugin/PluginInstaller.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginStoreViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
  Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml
Labels: enhancement

#3833 Add Empty Query Returning & Change ThemeSelector Keyword with ActionKeyword for Sys Plugin
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
Labels: enhancement

#2798 Semantic Version
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/Updater.cs
Labels: enhancement, Debug Only, no-pr-activity, Code Refactor

#3838 Fix message box vertically center issue when message type is not OK
  Flow.Launcher/MessageBoxEx.xaml.cs
Labels: bug, kind/ui

#3843 Add plugin update dialog for selective plugin updating
  Flow.Launcher.Core/Plugin/PluginInstaller.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/PluginUpdateWindow.xaml
  Flow.Launcher/PluginUpdateWindow.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginStoreViewModel.cs
Labels: enhancement

#3286 update to .net 9
  .github/workflows/default_plugins.yml
  .github/workflows/dotnet.yml
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/packages.lock.json
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/packages.lock.json
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Plugin/packages.lock.json
  Flow.Launcher.Test/Flow.Launcher.Test.csproj
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Properties/PublishProfiles/Net9.0-SelfContained.pubxml
  Flow.Launcher/Resources/SegoeFluentIcons.ttf
  Flow.Launcher/packages.lock.json
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
  Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
  Plugins/Flow.Launcher.Plugin.Url/Flow.Launcher.Plugin.Url.csproj
  Plugins/Flow.Launcher.Plugin.WebSearch/Flow.Launcher.Plugin.WebSearch.csproj
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Flow.Launcher.Plugin.WindowsSettings.csproj
  Scripts/flowlauncher.nuspec
  Scripts/post_build.ps1
  global.json
Labels: enhancement

#3850 Initialize language before portable clean up and plugin initialization
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Resource/Internationalization.cs
  Flow.Launcher/App.xaml.cs
Labels: enhancement, 10 min review

#3848 Improve Sys plugin & add APIs for getting user data and log locations
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
  Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
Labels: enhancement

#3846 Upgrade NuGet Dependencies & Package Lock Json Files
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/packages.lock.json
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/NativeMethods.txt
  Flow.Launcher.Infrastructure/Win32Helper.cs
  Flow.Launcher.Infrastructure/packages.lock.json
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Plugin/NativeMethods.txt
  Flow.Launcher.Plugin/SharedModels/MonitorInfo.cs
  Flow.Launcher.Plugin/packages.lock.json
  Flow.Launcher.Test/Flow.Launcher.Test.csproj
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Msg.xaml.cs
  Flow.Launcher/MsgWithButton.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/packages.lock.json
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/ProcessHelper.cs
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Program/Programs/ShellLocalization.cs
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
Labels: bug, dependencies, .NET

#3859 Smart thousands and decimals for Calculator
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
  Plugins/Flow.Launcher.Plugin.Calculator/MainRegexHelper.cs
  Plugins/Flow.Launcher.Plugin.Calculator/NumberTranslator.cs
  Plugins/Flow.Launcher.Plugin.Calculator/Views/CalculatorSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
Labels: enhancement, 20 min review

#3871 Fix typo in Calculator plugin
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/he.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
Labels: bug, 1 min review

#3872 Clear plugin list selection to make sure all items can be mouse hovered
  Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml
  Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml.cs
Labels: bug, enhancement, kind/ui
