Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2025-02, with the labels that each got.

#3230 add BackToQueryResults to JsonRPCPublicAPI
  Flow.Launcher.Core/Plugin/JsonRPCV2Models/JsonRPCPublicAPI.cs
Labels: enhancement

#3231 Fix unix directory seperator issue
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Constants.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Labels: bug, 1 min review

#3241 perf: hide main window from alt tab program switcher
  Flow.Launcher/Helper/WindowsInteropHelper.cs
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/NativeMethods.txt
Labels: 5 min review

#3233 Fix Plugin Store Page Refresh Issue
  Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginStoreViewModel.cs
Labels: bug, Small PR, 1 min review

#3170 Add New API for ProgressBoxEx to Show Progress & Add Progress Display for Plugin Downloading & Improve DownloadUrl Api Function
  Flow.Launcher.Core/Plugin/JsonRPCV2Models/JsonRPCPublicAPI.cs
  Flow.Launcher.Infrastructure/Http/Http.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/ProgressBoxEx.xaml
  Flow.Launcher/ProgressBoxEx.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
Labels: enhancement, kind/ux, 20 min review

#3238 Improve explorer path parse when path ends with backslash
  Flow.Launcher.Infrastructure/FileExplorerHelper.cs
Labels: enhancement

#3194 New API for Record Key of Results & Fix Result Clone Issue
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/Storage/TopMostRecord.cs
  Flow.Launcher/Storage/UserSelectedRecord.cs
Labels: bug, enhancement

#3110 Add `.`, `./lib`, `./plugin` directories to path for Python plugins
  Flow.Launcher.Core/Plugin/PythonPlugin.cs
  Flow.Launcher.Core/Plugin/PythonPluginV2.cs
Labels: 5 min review

#3225 Add Windows Terminal to Shell Plugins
  Plugins/Flow.Launcher.Plugin.Shell/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
  Plugins/Flow.Launcher.Plugin.Shell/Settings.cs
  Plugins/Flow.Launcher.Plugin.Shell/ShellSetting.xaml
  Plugins/Flow.Launcher.Plugin.Shell/ShellSetting.xaml.cs
Labels: enhancement

#3251 Use api function to hide window
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
Labels: enhancement, Small PR

#3203 Improve context menu item action response & Fix origin query null exception
  Flow.Launcher.Plugin/Query.cs
  Flow.Launcher/Storage/TopMostRecord.cs
  Flow.Launcher/Storage/UserSelectedRecord.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
Labels: bug, enhancement

#3232 Fix main window resize border thickness issue
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher/MainWindow.xaml
Labels: bug

#3246 Fix Exception When Getting Thumbnails
  Flow.Launcher.Infrastructure/Image/ThumbnailReader.cs
Labels: bug, 1 min review

#3250 Improve Shutdown & Restart & Hibernate in Sys Plugin
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.Sys/NativeMethods.txt
Labels: enhancement

#3260 Remove Useless Separate Line for Blank Settings Panel
  Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
  Flow.Launcher/ViewModel/PluginViewModel.cs
  Plugins/Flow.Launcher.Plugin.Url/Flow.Launcher.Plugin.Url.csproj
  Plugins/Flow.Launcher.Plugin.Url/Main.cs
  Plugins/Flow.Launcher.Plugin.Url/SettingsControl.xaml
  Plugins/Flow.Launcher.Plugin.Url/SettingsControl.xaml.cs
Labels: enhancement, kind/ui

#3248 Fix Custom Query Hotkey / Shortcuts Preview Issue
  Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
  Flow.Launcher/CustomShortcutSetting.xaml.cs
Labels: bug, 1 min review

#3262 Enable the use of Win hotkey to trigger flow
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/HotkeyControl.xaml.cs
  Flow.Launcher/HotkeyControlDialog.xaml.cs
Labels: enhancement

#3263 Add exception handling for register unregister hotkey
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/Languages/en.xaml
Labels: Dev branch only

#3257 Fix Issue that Plugin Cannot Cache Records
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, 1 min review

#3266 Make Message box Window to be Topmost
  Flow.Launcher.Core/MessageBoxEx.xaml
Labels: bug, kind/ui, Small PR

#3259 Support removing duplicated programs
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Settings.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
Labels: enhancement, 5 min review

#3240 Fix ChangeQuery & ReQuery Work Issue When Results Are Not From Query Results
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/PluginViewModel.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
Labels: bug, 1 min review

#3081 Reload Context
  Flow.Launcher.Core/Plugin/JsonRPCPluginV2.cs
Labels: bug, 1 min review

#3219 Support deleting plugin settings when uninstalling plugins
  Flow.Launcher.Core/Plugin/JsonRPCPluginBase.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Infrastructure/Storage/PluginJsonStorage.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
Labels: enhancement

#3177 resolve link before using File.Replace
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
Labels: bug, 1 min review

#3274 Fix dependency injection issue in installer
  Flow.Launcher/Flow.Launcher.csproj
Labels: bug

#3277 Add preview background in welcome page 2
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml.cs
Labels: bug

#3264 Improve Report Window Design
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/CustomShortcutSetting.xaml
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/PriorityChangeWindow.xaml
  Flow.Launcher/ReportWindow.xaml
  Flow.Launcher/ReportWindow.xaml.cs
  Flow.Launcher/SelectBrowserWindow.xaml
  Flow.Launcher/SelectFileManagerWindow.xaml
  Flow.Launcher/WelcomeWindow.xaml
Labels: bug, kind/ui, 5 min review

#3283 Fix System.PlatformNotSupportedException & Add exception message box in App constructor
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Flow.Launcher.csproj
Labels: bug, 1 min review

#3267 Improve Progress Box Design
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/ProgressBoxEx.xaml
  Flow.Launcher/ProgressBoxEx.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
Labels: kind/ui, 5 min review

#3279 Improve Wallpaper Retrieval
  Flow.Launcher/Helper/WallpaperPathRetrieval.cs
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
Labels: enhancement, 5 min review

#3297 Fix API instance create twice issue & Make PluginManager.API private
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/PluginViewModel.cs
Labels: bug
