Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2025-04, with the labels that each got.

#3406 Ungroup Item in general page
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
Labels: 1 min review

#3411 Add clean cache option & Add exception handler for cleaning folders
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml
Labels: 10 min review

#3417 Fix environment exit & Wait image cache save before restarting & Add settings saving lock & Do not crash when caught exception saving
  Flow.Launcher.Core/Configuration/Portable.cs
  Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
  Flow.Launcher.Core/Updater.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Infrastructure/Storage/FlowLauncherJsonStorage.cs
  Flow.Launcher.Infrastructure/Storage/PluginJsonStorage.cs
  Flow.Launcher.Infrastructure/Win32Helper.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Notification.cs
  Flow.Launcher/PublicAPIInstance.cs
Labels: bug, Dev branch only

#3375 Force FL window foreground when switching keyboard layout
  Flow.Launcher.Infrastructure/Win32Helper.cs
Labels: Dev branch only, 1 min review

#3422 Initialize HotKeyMapper after window is loaded & Wait image cache saved before closing main window
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug, 1 min review

#3419 New API Function from PluginManifest and PluginManager
  Flow.Launcher.Core/ExternalPlugins/CommunityPluginSource.cs
  Flow.Launcher.Core/ExternalPlugins/CommunityPluginStore.cs
  Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
  Flow.Launcher.Core/ExternalPlugins/UserPlugin.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher.Plugin/UserPlugin.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginStoreViewModel.cs
  Flow.Launcher/ViewModel/PluginStoreItemViewModel.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
  Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
  Plugins/Flow.Launcher.Plugin.PluginsManager/Utilities.cs
Labels: enhancement, 20 min review

#3412 New API Function LoadImageAsync
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/MessageBoxEx.xaml.cs
  Flow.Launcher/Msg.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/PluginViewModel.cs
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/PreviewPanel.xaml.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceViewModel.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Baidu.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Bing.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/DuckDuckGo.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Google.cs
Labels: enhancement, 5 min review

#3408 New API Function LogError
  Flow.Launcher.Core/Plugin/JsonRPCV2Models/JsonRPCPublicAPI.cs
  Flow.Launcher.Infrastructure/Logger/Log.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
Labels: enhancement

#3410 New API Functions Plugin Cache Storage & Use API Functions for Program Plugin & Remove Reflection with Interfaces
  Flow.Launcher.Core/Plugin/JsonRPCV2Models/JsonRPCPublicAPI.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Storage/IRemovable.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Infrastructure/Storage/BinaryStorage.cs
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
  Flow.Launcher.Infrastructure/Storage/PluginBinaryStorage.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher.Plugin/Interfaces/ISavable.cs
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWPPackage.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/Commands/ProgramSettingDisplay.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
Labels: enhancement, 20 min review

#3431 Set max result lower limit to 1
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
Labels: bug

#3429 New API Function from Stopwatch & Improve Program Plugin
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Infrastructure/Stopwatch.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
Labels: enhancement

#3361 Support Svg File Icon Loading & Local favicon for bookmark plugin
  Flow.Launcher.Core/Resource/LocalizationConverter.cs
  Flow.Launcher.Core/Resource/LocalizedDescriptionAttribute.cs
  Flow.Launcher.Core/Resource/TranslationConverter.cs
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/Image/ImageCache.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Infrastructure/NativeMethods.txt
  Flow.Launcher.Infrastructure/UI/EnumBindingSource.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher.Plugin/KeyEvent.cs
  Flow.Launcher.Plugin/NativeMethods.txt
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginStoreViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginsViewModel.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/BookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/FirefoxBookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Models/Bookmark.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/SettingsControl.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndex.cs
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/UWPPackage.cs
  Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
  Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/Flow.Launcher.Plugin.WebSearch.csproj
Labels: enhancement, Documentation, Dev branch only, 20 min review

#3435 Dependency Code Quality
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Resource/InternationalizationManager.cs
  Flow.Launcher.Core/Updater.cs
  Flow.Launcher/ActionKeywords.xaml.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Converters/TextConverter.cs
  Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
  Flow.Launcher/CustomShortcutSetting.xaml.cs
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/HotkeyControl.xaml.cs
  Flow.Launcher/HotkeyControlDialog.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage1.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneHotkeyViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneProxyViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: 5 min review, Code Quality

#3432 Fix JsonRpc plugin connection loss exception
  Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
  Flow.Launcher.Core/Plugin/JsonRPCPluginBase.cs
  Flow.Launcher.Core/Plugin/JsonRPCPluginV2.cs
Labels: bug, 1 min review, Code Quality

#3447 Adjust Numberbox Design & Revert PositionResetToolTip string
  Flow.Launcher/Converters/QuerySuggestionBoxConverter.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Resources/Controls/InstalledPluginDisplay.xaml
  Flow.Launcher/Resources/CustomControlTemplate.xaml
Labels: kind/ui, Dev branch only, kind/ux

#3426 Korean IME Infobar
  Flow.Launcher.Infrastructure/Win32Helper.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Resources/Controls/InfoBar.xaml
  Flow.Launcher/Resources/Controls/InfoBar.xaml.cs
  Flow.Launcher/Resources/Dark.xaml
  Flow.Launcher/Resources/Light.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
Labels: bug, kind/ui, kind/ux, 20 min review

#3450 Fix explorer settings panel margin
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
Labels: Dev branch only

#3452 Fix storage save directory issue
  Flow.Launcher.Infrastructure/Storage/BinaryStorage.cs
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
Labels: Dev branch only

#3456 Improve FL Exiting & Exception Handler
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Resource/Internationalization.cs
  Flow.Launcher.Infrastructure/Storage/BinaryStorage.cs
  Flow.Launcher.Infrastructure/Storage/FlowLauncherJsonStorage.cs
  Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Helper/ErrorReporting.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
Labels: bug, 5 min review

#567 Introduce new search order - System.Search.Rank - for Explorer plugin
  Flow.Launcher.Test/Plugins/ExplorerTest.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/QueryConstructor.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndexSearchManager.cs
Labels: enhancement

#3438 Result Badge
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/Converters/BadgePositionConverter.cs
  Flow.Launcher/Converters/SizeRatioConverter.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
  Flow.Launcher/Themes/Win11Light.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
Labels: bug, enhancement, kind/ui

#3460 Improve log & Ignore plugin source http exception
  Flow.Launcher.Core/Configuration/Portable.cs
  Flow.Launcher.Core/ExternalPlugins/CommunityPluginSource.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/AbstractPluginEnvironment.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/JavaScriptEnvironment.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/JavaScriptV2Environment.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/PythonEnvironment.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/TypeScriptEnvironment.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/TypeScriptV2Environment.cs
  Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
  Flow.Launcher.Core/Plugin/PluginConfig.cs
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Plugin/PluginsLoader.cs
  Flow.Launcher.Core/Plugin/ProcessStreamPluginV2.cs
  Flow.Launcher.Core/Resource/Internationalization.cs
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher.Core/Updater.cs
  Flow.Launcher.Infrastructure/Http/Http.cs
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Infrastructure/Logger/Log.cs
  Flow.Launcher.Infrastructure/Stopwatch.cs
  Flow.Launcher.Infrastructure/Storage/BinaryStorage.cs
  Flow.Launcher.Infrastructure/Storage/FlowLauncherJsonStorage.cs
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
  Flow.Launcher.Infrastructure/Storage/PluginBinaryStorage.cs
  Flow.Launcher.Infrastructure/Storage/PluginJsonStorage.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Converters/QuerySuggestionBoxConverter.cs
  Flow.Launcher/Helper/AutoStartup.cs
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/Helper/WallpaperPathRetrieval.cs
  Flow.Launcher/MessageBoxEx.xaml.cs
  Flow.Launcher/Msg.xaml.cs
  Flow.Launcher/Notification.cs
  Flow.Launcher/ProgressBoxEx.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/ReportWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultViewModel.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
  Plugins/Flow.Launcher.Plugin.ProcessKiller/ProcessHelper.cs
  Plugins/Flow.Launcher.Plugin.Program/Main.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Baidu.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Bing.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/DuckDuckGo.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Google.cs
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Log.cs
Labels: Dev branch only, Code Quality

#3465 Add sponsor
  README.md
Labels: enhancement

#3466 Fix Content Dialog owner & Fix Win32Exception
  Flow.Launcher.Infrastructure/Win32Helper.cs
  Flow.Launcher/HotkeyControl.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginsViewModel.cs
Labels: bug

#3467 Fix Dialog Owner & Improve Window Exiting & Improve WindowsThumbnailProvider & Fix Warnings
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Infrastructure/Image/ThumbnailReader.cs
  Flow.Launcher/Msg.xaml.cs
  Flow.Launcher/ReportWindow.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginsViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml.cs
  Flow.Launcher/ViewModel/RelayCommand.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Helper/ShellContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Helper/SortOptionTranslationHelper.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/EnvironmentVariables.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/ActionKeywordModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/RelayCommand.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Sys/Main.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml.cs
Labels: bug, Dev branch only

#3458 Import Theme Size / Select Default Font / Small Design Fixes
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Infrastructure/Win32Helper.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/Resources/Dark.xaml
  Flow.Launcher/Resources/Light.xaml
  Flow.Launcher/ResultListBox.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/Themes/Base.xaml
  Flow.Launcher/Themes/Circle System.xaml
  Flow.Launcher/Themes/SlimLight.xaml
  Flow.Launcher/Themes/Win11Light.xaml
Labels: bug, enhancement, kind/ui

#3472 Fix Possible Window Popup During Startup & Fix Store Plugin List Refresh Issue
  Flow.Launcher.Core/ExternalPlugins/CommunityPluginSource.cs
  Flow.Launcher.Core/ExternalPlugins/CommunityPluginStore.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Helper/AutoStartup.cs
  Flow.Launcher/Helper/HotKeyMapper.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
Labels: Dev branch only

#2986 GitHub action
  .github/workflows/dotnet.yml
  Scripts/post_build.ps1
Labels: 5 min review

#3477 Rename ‘Search Window Position’ to ‘Search Window Location’
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/Resources/Light.xaml
Labels: kind/ui

#3478 Deploy website on release
  .github/workflows/website_deploy.yml
Labels: enhancement, CI/CD

#3479 Fix typo
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
Labels: kind/i18n, 1 min review

#3470 Add Setting for Changing Font in Settings Window
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Infrastructure/Win32Helper.cs
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
  Flow.Launcher/CustomShortcutSetting.xaml
  Flow.Launcher/CustomShortcutSetting.xaml.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SelectBrowserWindow.xaml
  Flow.Launcher/SelectBrowserWindow.xaml.cs
  Flow.Launcher/SelectFileManagerWindow.xaml
  Flow.Launcher/SelectFileManagerWindow.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: 10 min review

#3487 Improve Setting Window Font & Format xaml styles & Fix log message & Improve code quality
  Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/ActionKeywords.xaml
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/CustomQueryHotkeySetting.xaml
  Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
  Flow.Launcher/CustomShortcutSetting.xaml
  Flow.Launcher/CustomShortcutSetting.xaml.cs
  Flow.Launcher/Helper/AutoStartup.cs
  Flow.Launcher/HotkeyControl.xaml
  Flow.Launcher/HotkeyControlDialog.xaml
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Resources/Controls/HotkeyDisplay.xaml
  Flow.Launcher/Resources/Controls/HotkeyDisplay.xaml.cs
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/Resources/Pages/WelcomePage1.xaml
  Flow.Launcher/Resources/Pages/WelcomePage1.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage3.xaml
  Flow.Launcher/Resources/Pages/WelcomePage3.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage4.xaml
  Flow.Launcher/Resources/Pages/WelcomePage4.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage5.xaml
  Flow.Launcher/Resources/Pages/WelcomePage5.xaml.cs
  Flow.Launcher/SelectBrowserWindow.xaml
  Flow.Launcher/SelectBrowserWindow.xaml.cs
  Flow.Launcher/SelectFileManagerWindow.xaml
  Flow.Launcher/SelectFileManagerWindow.xaml.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginStoreViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneProxyViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneHotkey.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml
  Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml
  Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneProxy.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneProxy.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml.cs
  Flow.Launcher/SettingWindow.xaml
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
  Flow.Launcher/ViewModel/WelcomeViewModel.cs
  Flow.Launcher/WelcomeWindow.xaml
  Flow.Launcher/WelcomeWindow.xaml.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/CustomBrowserSetting.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml
  Plugins/Flow.Launcher.Plugin.Program/AddProgramSource.xaml
  Plugins/Flow.Launcher.Plugin.Program/ProgramSuffixes.xaml
Labels: bug, enhancement, kind/ui, Dev branch only, Code Quality

#3482 Fix clock not displaying in certain situations
  Flow.Launcher/MainWindow.xaml.cs
Labels: kind/ui, Dev branch only

#3485 Fix NumberBox Placeholder text color
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Flow.Launcher/Resources/Dark.xaml
Labels: kind/ui, Dev branch only

#3491 Add cache folder button in dev tools
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml
Labels: kind/ui

#3494 Support filtering dotnet, python, node.js, executable plugins
  Flow.Launcher.Plugin/AllowedLanguage.cs
  Flow.Launcher/Images/EXE.png
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginStoreViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml
  Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml.cs
Labels: enhancement

#3495 Improve PropertyChanged.Fody Code Quality
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher/ActionKeywords.xaml.cs
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/ViewModel/PluginViewModel.cs
Labels: Code Quality

#3499 Fix clean cache issue
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
Labels: Dev branch only
