Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2025-05, with the labels that each got.

#3314 Fix copy to clipboard STA thread issue & Support retry for copy & Async build-in shortcut model & Fix build shortcuts text replace issue & Fix startup window hide issue
  Flow.Launcher.Core/Plugin/QueryBuilder.cs
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher.Infrastructure/NativeMethods.txt
  Flow.Launcher.Infrastructure/UserSettings/CustomShortcutModel.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Infrastructure/Win32Helper.cs
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher.Plugin/Query.cs
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/Helper/DataWebRequestFactory.cs
  Flow.Launcher/Helper/ErrorReporting.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginStoreViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginsViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml
  Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, enhancement, review in progress, Dev branch only, 10 min review

#3503 Do not query again when setting private field of QueryText
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: Dev branch only

#3509 Add more debug log info for query
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, 1 min review

#3399 Support Querying Results When Query Text is Empty
  Flow.Launcher.Core/Plugin/PluginManager.cs
  Flow.Launcher.Core/Plugin/QueryBuilder.cs
  Flow.Launcher.Infrastructure/UserSettings/PluginSettings.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher.Plugin/Interfaces/IAsyncHomeQuery.cs
  Flow.Launcher.Plugin/Interfaces/IHomeQuery.cs
  Flow.Launcher.Plugin/PluginMetadata.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/Resources/Controls/InstalledPluginDisplay.xaml
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginsViewModel.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/PluginViewModel.cs
  Plugins/Flow.Launcher.Plugin.PluginIndicator/Main.cs
Labels: enhancement, Documentation, kind/ux

#3513 Fix result missing + not updating issues
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: Dev branch only

#3521 Fix startup flicker
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/MainWindow.xaml.cs
Labels: Dev branch only

#3524 Fix clearing of results logic & minor adjustment to results update
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultsForUpdate.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
Labels: bug, kind/ux, 1 min review

#3528 Check spelling workflow ignore release PR targeting master branch
  .github/workflows/spelling.yml
Labels: bug, CI/CD

#3527 Adjust margin in appearance page
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
Labels: kind/ui, Dev branch only

#3529 Fix Homepage with triggers history results on arrow up
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: Dev branch only

#3530 Fix null origin query issue
  Flow.Launcher/Storage/TopMostRecord.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: bug, Dev branch only

#3526 Support copy file name
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
Labels: enhancement

#3532 Fix sound effect issue after sleep or hibernation
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug

#3535 Fix temp files deleting issue & Validate the cache directory before loading all bookmarks
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
Labels: Dev branch only

#3536 Do not show error message for initialization if plugin is already disabled
  Flow.Launcher.Core/Plugin/PluginManager.cs
Labels: bug, 1 min review

#3540 Disable auto restart after plugin install by default
  Plugins/Flow.Launcher.Plugin.PluginsManager/Settings.cs
Labels: bug

#3538 Fix results context menu display issue
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
Labels: bug

#3537 Fix Vertical Window Positioning with Multiple Monitors
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingWindow.xaml.cs
Labels: bug

#3500 Support Multiple Topmost Records
  Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
  Flow.Launcher/Storage/TopMostRecord.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
Labels: enhancement

#3543 Fix system ColorScheme update handling
  Flow.Launcher/MainWindow.xaml.cs
Labels: kind/ui, Dev branch only, 1 min review

#3539 Improve Program plugin delete button logic
  Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
  Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
Labels: bug, enhancement, 5 min review

#3545 Add dynamic font family to SettingWindow
  Flow.Launcher/SettingWindow.xaml
Labels: kind/ui, Dev branch only

#3547 Fix setting window navigation update issue
  Flow.Launcher/Resources/Pages/WelcomePage1.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage2.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage3.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage4.xaml.cs
  Flow.Launcher/Resources/Pages/WelcomePage5.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneHotkey.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneProxy.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml.cs
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Labels: bug, 20 min review

#3549 initialize position before InitializeComponent
  Flow.Launcher/SettingWindow.xaml.cs
Labels: bug, Dev branch only, 1 min review

#3552 Fix prevent zombie explorer.exe processes when opening folders
  Flow.Launcher/PublicAPIInstance.cs
Labels: bug

#3531 New Crowdin updates
  Flow.Launcher/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/he.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ar.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/cs.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/da.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/de.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/es-419.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/es.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/fr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/he.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/it.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ko.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/nb.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/nl.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/pl.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/pt-br.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/pt-pt.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/ru.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/sk.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/sr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/tr.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/uk-UA.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/vi.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-cn.xaml
  Plugins/Flow.Launcher.Plugin.Program/Languages/zh-tw.xaml
Labels: bug, kind/i18n

#3553 Fix result clearing for non-query calls and home page + history results page toggling
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
Labels: Dev branch only

#3558 Unify all default built-in plugins' version
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
  Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
  Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
  Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
  Plugins/Flow.Launcher.Plugin.Program/plugin.json
  Plugins/Flow.Launcher.Plugin.Shell/plugin.json
  Plugins/Flow.Launcher.Plugin.Sys/plugin.json
  Plugins/Flow.Launcher.Plugin.Url/plugin.json
  Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
  Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
  appveyor.yml
Labels: enhancement, CI/CD

#3568 Fix: Ensure QueryTextBox receives focus after Win+R
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Plugins/Flow.Launcher.Plugin.Shell/Main.cs
Labels: bug

#3559 New Crowdin updates
  Flow.Launcher/Languages/ar.xaml
  Flow.Launcher/Languages/cs.xaml
  Flow.Launcher/Languages/da.xaml
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/fr.xaml
  Flow.Launcher/Languages/he.xaml
  Flow.Launcher/Languages/it.xaml
  Flow.Launcher/Languages/ja.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/nl.xaml
  Flow.Launcher/Languages/pl.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/ru.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/sr.xaml
  Flow.Launcher/Languages/tr.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/vi.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.ja-JP.resx
Labels: bug, kind/i18n

#3570 Fix main window null when checking exiting
  Flow.Launcher/App.xaml.cs
  Flow.Launcher/SettingWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/WelcomeWindow.xaml.cs
Labels: bug, Dev branch only

#3560 Version bump for release
  appveyor.yml
Labels: release

#3579 Display the file age in preview panel
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/PreviewPanel.xaml.cs
Labels: enhancement, kind/ui

#3600 Use ResultContextMenu instead of ContextMenu
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
  Flow.Launcher/Themes/Base.xaml
Labels: Code Quality
