Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2025-06, with the labels that each got.

#3603 Update Advanced title and reset button content to use dynamic resources
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml
Labels: kind/ui, kind/i18n, 1 min review

#3604 Use try-catch to resolve SendAsync issue
  Flow.Launcher.Infrastructure/Http/Http.cs
Labels: Dev branch only

#3588 Use new model to clear results & Fix clear existing results when using IResultUpdate
  Flow.Launcher.Core/Plugin/QueryBuilder.cs
  Flow.Launcher.Plugin/Query.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultsForUpdate.cs
  Flow.Launcher/ViewModel/ResultsViewModel.cs
Labels: Dev branch only

#3607 Add release PR workflow to auto update PR description
  .github/update_release_pr.py
  .github/workflows/release_pr.yml
Labels: enhancement, CI/CD

#3584 Fix argument null exception when updating plugin directories for erroneous plugins
  Flow.Launcher.Core/Plugin/PluginManager.cs
Labels: Dev branch only, 1 min review

#3610 Use dynamic resource instead of binding
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
Labels: bug

#3609 New Crowdin updates
  Flow.Launcher/Languages/vi.xaml
Labels: bug, kind/i18n

#3612 Version bump Plugin
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
Labels: release

#3627 Silent handle TaskSchedulerUnobservedTaskException
  Flow.Launcher/Helper/ErrorReporting.cs
Labels: bug, 1 min review

#3639 Fix OpenUri Exception
  Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/PublicAPIInstance.cs
Labels: bug, 1 min review

#3606 Fix issues related to window maximization and Snap behavior
  Flow.Launcher.Core/Resource/Theme.cs
  Flow.Launcher/MainWindow.xaml.cs
Labels: bug

#3652 Use PInvoke & Improve code comments & Use switch sentences
  Flow.Launcher.Infrastructure/NativeMethods.txt
  Flow.Launcher.Infrastructure/Win32Helper.cs
  Flow.Launcher/MainWindow.xaml.cs
Labels: Dev branch only

#3656 Update default plugin publish to follow production version
  .github/workflows/default_plugins.yml
Labels: bug

#3611 Add get PR authors to workflow
  .github/update_release_pr.py
Labels: bug

#3658 Do not show UI when shortcuts cannot be resolved
  Plugins/Flow.Launcher.Plugin.Program/Programs/ShellLinkHelper.cs
Labels: bug

#3655 Catch exception when installing Everything
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchManager.cs
Labels: bug

#3666 Replace TabControl with Expander in Explorer Plugin Setting Panel
  Flow.Launcher/Resources/CustomControlTemplate.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
Labels: bug, kind/ui, 5 min review

#3595 Remove obsolete TranslationConverter & project reference in Explorer plugin
  Flow.Launcher.Core/Resource/TranslationConverter.cs
  Flow.Launcher.Infrastructure/UserSettings/CustomShortcutModel.cs
  Flow.Launcher/Resources/SettingWindowStyle.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneHotkey.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/ActionKeywordModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
Labels: bug

#3668 Fix Derive Class Save Method Calling Issue
  Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
  Flow.Launcher.Infrastructure/Storage/FlowLauncherJsonStorage.cs
  Flow.Launcher.Infrastructure/Storage/PluginBinaryStorage.cs
  Flow.Launcher.Infrastructure/Storage/PluginJsonStorage.cs
  Flow.Launcher/PublicAPIInstance.cs
Labels: bug, 1 min review

#3541 Support Showing Search Window at Topmost
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
Labels: enhancement, 5 min review

#3694 Update Button width for responsive design
  Flow.Launcher/Resources/Controls/InstalledPluginDisplayKeyword.xaml
Labels: bug, kind/ui

#3718 Delete resx files
  Flow.Launcher/Properties/Resources.fr-FR.resx
  Flow.Launcher/Properties/Resources.he-IL.resx
Labels: bug, 1 min review

#3705 Remove on tag release upload & change NuGet publish to on master push
  appveyor.yml
Labels: bug

#3664 Support Loading Msix FireFox Bookmarks & Fix IsRelative logic
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/FirefoxBookmarkLoader.cs
Labels: bug

#3674 BrowserBookmark do not use SqliteConnection pooling to avoid ObjectDisposedException
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/FirefoxBookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Helper/FaviconHelper.cs
Labels: Dev branch only

#3616 Add New API to Force Web Url
  Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
  Flow.Launcher/PublicAPIInstance.cs
  Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
Labels: bug, review in progress, 1 min review

#3726 Merge release v1.20.1 back to dev
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  appveyor.yml
Labels: release

#3702 Refactor ActionKeywords UI and improve keyword handling
  Flow.Launcher/ActionKeywords.xaml
  Flow.Launcher/ActionKeywords.xaml.cs
Labels: enhancement, Code Refactor

#3729 Add AppVeyor skip build on tag
  appveyor.yml
Labels: bug, CI/CD

#3728 Improve Topmost Feature
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
Labels: enhancement

#3712 Add preview information back for external preview
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
Labels: Dev branch only

#3737 Fix tab sequence
  Flow.Launcher/CustomShortcutSetting.xaml
Labels: bug

#3745 Fix false failing spell check rules
  .github/actions/spelling/expect.txt
  .github/actions/spelling/patterns.txt
Labels: bug

#3774 Calculator: Support hex numbers
  Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
Labels: enhancement

#3780 Add Separator and margin in release note
  Flow.Launcher/ReleaseNotesWindow.xaml.cs
Labels: Dev branch only, 1 min review

#3779 Fix Card Control
  Flow.Launcher/Resources/Controls/Card.xaml
  Flow.Launcher/Resources/Controls/Card.xaml.cs
  Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneHotkey.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneProxy.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
Labels: Dev branch only

#3781 Update Calculator plugin description
  Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
Labels: Dev branch only

#3782 Support volume type for quick access link
  Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/QuickAccess.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Labels: enhancement

#3786 Fix Plugin Uninstallation Issue
  Flow.Launcher.Core/Plugin/PluginManager.cs
Labels: bug
