Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2025-09, with the labels that each got.

#3932 Allow setting of minimum app version plugin requirement
  Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
  Flow.Launcher.Plugin/UserPlugin.cs
Labels: enhancement

#3933 Switch plugins manifest file download URL to be from main branch
  Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
Labels: enhancement

#3936 Add maximum results shown warning when always preview is on
  Flow.Launcher/Languages/en.xaml
  Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
Labels: bug

#3940 New Crowdin updates
  Flow.Launcher/Languages/ar.xaml
  Flow.Launcher/Languages/cs.xaml
  Flow.Launcher/Languages/da.xaml
  Flow.Launcher/Languages/de.xaml
  Flow.Launcher/Languages/es-419.xaml
  Flow.Launcher/Languages/es.xaml
  Flow.Launcher/Languages/fr.xaml
  Flow.Launcher/Languages/he.xaml
  Flow.Launcher/Languages/it.xaml
  Flow.Launcher/Languages/ja.xaml
  Flow.Launcher/Languages/ko.xaml
  Flow.Launcher/Languages/nb.xaml
  Flow.Launcher/Languages/nl.xaml
  Flow.Launcher/Languages/pl.xaml
  Flow.Launcher/Languages/pt-br.xaml
  Flow.Launcher/Languages/pt-pt.xaml
  Flow.Launcher/Languages/ru.xaml
  Flow.Launcher/Languages/sk.xaml
  Flow.Launcher/Languages/sr-Cyrl-RS.xaml
  Flow.Launcher/Languages/sr.xaml
  Flow.Launcher/Languages/tr.xaml
  Flow.Launcher/Languages/uk-UA.xaml
  Flow.Launcher/Languages/vi.xaml
  Flow.Launcher/Languages/zh-cn.xaml
  Flow.Launcher/Languages/zh-tw.xaml
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Calculator/Languages/ja.xaml
  Plugins/Flow.Launcher.Plugin.Sys/Languages/ja.xaml
Labels: bug, kind/i18n

#3929 Bump version for 2.0.0 release + update readme
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  README.md
  appveyor.yml
Labels: release

#3906 Upgrade Nuget packages & Update lock files
  Flow.Launcher.Core/Flow.Launcher.Core.csproj
  Flow.Launcher.Core/packages.lock.json
  Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
  Flow.Launcher.Infrastructure/packages.lock.json
  Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
  Flow.Launcher.Plugin/packages.lock.json
  Flow.Launcher.Test/Flow.Launcher.Test.csproj
  Flow.Launcher/Flow.Launcher.csproj
  Flow.Launcher/packages.lock.json
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
  Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
  Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
Labels: bug, dependencies

#3975 Catch scary exception, print friendly log
  Flow.Launcher.Core/ExternalPlugins/CommunityPluginSource.cs
Labels: bug

#3976 Enhanced logging
  Flow.Launcher.Infrastructure/Logger/Log.cs
  Flow.Launcher.Infrastructure/UserSettings/Settings.cs
  Flow.Launcher/Languages/en.xaml
Labels: bug, enhancement

#3979 Improve JsonRPC Plugin Setting Panel
  Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
Labels: bug, enhancement, kind/ui, 1 min review

#3985 Fix AllEverythingSortOptions issue
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
Labels: bug, kind/ui

#3986 Fix Wallpaper File Lock
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher/Helper/WallpaperPathRetrieval.cs
Labels: bug, 1 min review

#3993 Use Debug instead of Info
  Flow.Launcher.Core/ExternalPlugins/CommunityPluginSource.cs
Labels: Dev branch only

#3997 Use Flow.Launcher.Localization to improve code quality
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
  Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
  Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingDownloadHelper.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndexSearchManager.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
  Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/PreviewPanel.xaml.cs
  Plugins/Flow.Launcher.Plugin.Explorer/Views/QuickAccessLinkSettings.xaml.cs
Labels: Code Quality

#3999 Fix PortableMode Check Issue
  Flow.Launcher.Infrastructure/UserSettings/DataLocation.cs
  Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
Labels: bug

#4001 Merge v2.0.1 back into dev
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
  appveyor.yml
Labels: release
