Repository Flow-Launcher/Flow.Launcher, pull requests merged in 2025-08, with the labels that each got.

#3826 Fix BrowserBookmark '100% CPU' issue
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/FirefoxBookmarkLoader.cs
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Helper/FaviconHelper.cs
Labels: bug, enhancement, 10 min review

#3867 Do not create customized preview panel when preview is off
  Flow.Launcher/MainWindow.xaml
  Flow.Launcher/ViewModel/MainViewModel.cs
  Flow.Launcher/ViewModel/ResultViewModel.cs
Labels: bug, enhancement, 1 min review

#3902 Clean orphan files, temp fix
  Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
Labels: Dev branch only

#3900 Add error handler for DroplexPackage.Drop
  Flow.Launcher.Core/ExternalPlugins/Environments/PythonEnvironment.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/TypeScriptEnvironment.cs
  Flow.Launcher.Core/ExternalPlugins/Environments/TypeScriptV2Environment.cs
  Flow.Launcher/Languages/en.xaml
Labels: bug

#3860 Add Srpski (Cyrillic)
  Flow.Launcher.Core/Resource/AvailableLanguages.cs
Labels: enhancement

#3899 Add new api Result.QuerySuggestionText
  Flow.Launcher.Plugin/Result.cs
  Flow.Launcher/Converters/QuerySuggestionBoxConverter.cs
Labels: enhancement

#3898 Load images into ImageCache & Use non-async method in ImageCache
  Flow.Launcher.Infrastructure/Image/ImageLoader.cs
  Flow.Launcher.Infrastructure/Storage/BinaryStorage.cs
  Flow.Launcher/MainWindow.xaml.cs
  Flow.Launcher/PublicAPIInstance.cs
Labels: enhancement, 10 min review, Code Quality
